'use strict';
var ENGLISH_125=[
/* ============ A1 = 25 УРОКОВ ============ */
{id:'a1_01',level:'A1',title:'Алфавит, звуки и IPA',theory:'**26 букв, 44 звука.** Английский — не фонетический: "through" = /θruː/, "though" = /ðəʊ/.\n\n**Ключевые звуки IPA:**\n• /θ/ — think, three, thank\n• /ð/ — this, that, mother\n• /ŋ/ — sing, thing, long\n• /æ/ — cat, bad, apple\n• /ɪ/ vs /iː/ — ship vs sheep\n• /w/ vs /v/ — west vs vest\n\n**Правило:** гласная + согласная + e = долгий звук: make, bike, note.',practice:'Произнеси 10 пар: ship/sheep, bad/bed, cat/cut, west/vest, think/sink.',memory:'Мнемоника: /θ/ — язык между зубами, как "с" с шепелявостью. /ð/ — то же, но с голосом.',keywords:'alphabet, IPA, phonetics, pronunciation'},
{id:'a1_02',level:'A1',title:'Приветствия и знакомство',theory:'**Формальные:** Good morning (до 12:00), Good afternoon (12-18), Good evening (после 18).\n\n**Неформальные:** Hi, Hey, What\'s up?, How\'s it going?\n\n**Диалог-шаблон:**\n— Hi! I\'m Alex. Nice to meet you.\n— Nice to meet you too. I\'m Maria.\n— Where are you from?\n— I\'m from Russia. And you?',practice:'Составь диалог знакомства с 5 репликами.',memory:'Свяжи приветствие со временем.',keywords:'greetings, introduce'},
{id:'a1_03',level:'A1',title:'Числа 1-100 и даты',theory:'**1-12:** one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve.\n\n**13-19 = -teen.** **Десятки = -ty** (forty без u!).\n\n**Даты:** on the 5th of May.',practice:'Назови: 7, 13, 21, 45, 87, 100, 2024.',memory:'13-19 = teen, 20-90 = ty.',keywords:'numbers, dates'},
{id:'a1_04',level:'A1',title:'Цвета и оттенки',theory:'**Базовые:** red, blue, green, yellow, black, white, orange, pink, purple, brown, gray, gold, silver.\n\n**Идиомы:** I feel blue, Green with envy, Out of the blue.',practice:'Опиши 5 предметов вокруг.',memory:'Цвета ассоциируй с эмоциями.',keywords:'colors, idioms'},
{id:'a1_05',level:'A1',title:'Семья и родственники',theory:'**Immediate:** mother, father, sister, brother, son, daughter.\n\n**Extended:** grandmother, grandfather, aunt, uncle, cousin, nephew, niece.\n\n**In-laws:** mother-in-law, brother-in-law.',practice:'Нарисуй семейное древо.',memory:'-in-law = через брак.',keywords:'family'},
{id:'a1_06',level:'A1',title:'Еда, напитки, ресторан',theory:'**Meals:** breakfast, lunch, dinner, snack.\n\n**Food:** bread, meat, fish, rice, pasta, egg, cheese.\n\n**Drinks:** water, tea, coffee, juice, milk.',practice:'Составь меню на день.',memory:'Группируй по категориям.',keywords:'food, restaurant'},
{id:'a1_07',level:'A1',title:'Глагол to be',theory:'**Формы:** am / is / are.\n\nI am → I\'m. You are → You\'re. He is → He\'s.\n\n**Отрицание:** isn\'t / aren\'t. **Вопрос:** Am I? Is he?',practice:'10 предложений с разными подлежащими.',memory:'I→am, He/She/It→is.',keywords:'to be'},
{id:'a1_08',level:'A1',title:'Present Simple — привычки',theory:'**Формула:** Subject + V(s/es).\n\nHe work**s**. She work**s**.\n\n**Маркеры:** always, usually, often, sometimes, never.',practice:'10 предложений о своём дне.',memory:'He/She/It → +s.',keywords:'present simple'},
{id:'a1_09',level:'A1',title:'Артикли a/an/the',theory:'**a** — согласный звук. **an** — гласный звук. **the** — конкретный.\n\n**Без артикля:** имена, города, страны.',practice:'Вставь артикли.',memory:'a/an = один из многих.',keywords:'articles'},
{id:'a1_10',level:'A1',title:'Множественное число',theory:'**+s** обычно. **+es** после s,x,ch,sh. **y→ies**.\n\n**Исключения:** man→men, woman→women, child→children, foot→feet, tooth→teeth.',practice:'Образуй мн. число.',memory:'Исключения пой как рифму.',keywords:'plurals'},
{id:'a1_11',level:'A1',title:'This / That / These / Those',theory:'**this** этот, **that** тот, **these** эти, **those** те.',practice:'Опиши 5 предметов.',memory:'this/these = близко.',keywords:'demonstratives'},
{id:'a1_12',level:'A1',title:'Притяжательные и \'s',theory:'**my, your, his, her, its, our, their.**\n\n**\'s** — принадлежность.',practice:'Опиши вещи.',memory:'my=мой, your=твой.',keywords:'possessives'},
{id:'a1_13',level:'A1',title:'Предлоги места',theory:'**in** внутри, **on** на, **under** под, **next to** рядом, **between** между.',practice:'Опиши комнату.',memory:'Визуализируй кота.',keywords:'prepositions'},
{id:'a1_14',level:'A1',title:'Время и часы',theory:'**O\'clock** ровно, **Quarter past** 15 после, **Half past** 30, **Quarter to** 15 до.',practice:'Назови время.',memory:'past = после, to = до.',keywords:'time'},
{id:'a1_15',level:'A1',title:'Дни, месяцы, времена года',theory:'**Дни:** Monday-Sunday. **Месяцы:** January-December. **Сезоны:** spring, summer, autumn, winter.',practice:'Скажи свой день рождения.',memory:'Пой песню.',keywords:'days, months'},
{id:'a1_16',level:'A1',title:'Can / Can\'t',theory:'**Can** — умение. **Can\'t** — не могу.\n\nCan you help? Yes, I can.',practice:'Расскажи 5 умений.',memory:'Can = могу.',keywords:'can'},
{id:'a1_17',level:'A1',title:'Like / Don\'t like',theory:'**Like** нравится. **Love** очень. **Don\'t like** не. **Hate** ненавижу.\n\nПосле like + V-ing: I like reading.',practice:'Расскажи про 5 вещей.',memory:'Like + -ing.',keywords:'likes'},
{id:'a1_18',level:'A1',title:'Профессии и работа',theory:'teacher, doctor, engineer, lawyer, nurse, driver, cook, waiter, artist, programmer.\n\nWhat do you do? I\'m a teacher.',practice:'Назови 5 профессий.',memory:'Группируй по сферам.',keywords:'jobs'},
{id:'a1_19',level:'A1',title:'Хобби и свободное время',theory:'reading, sports, music, dancing, cooking, traveling.\n\nI like reading. My hobby is painting.',practice:'Расскажи про 3 хобби.',memory:'Визуализируй себя.',keywords:'hobbies'},
{id:'a1_20',level:'A1',title:'Погода',theory:'It\'s sunny / rainy / snowy / cloudy / windy. It\'s cold / warm / hot.',practice:'Опиши погоду.',memory:'It is + прилагательное.',keywords:'weather'},
{id:'a1_21',level:'A1',title:'В магазине',theory:'Can I help you? I\'d like..., How much is it? Cash/card.',practice:'Разыграй диалог.',memory:'I\'d like = я хотел бы.',keywords:'shopping'},
{id:'a1_22',level:'A1',title:'В кафе и ресторане',theory:'Are you ready to order? I\'d like a coffee. The bill, please.',practice:'Составь заказ.',memory:'I\'d like = вежливо.',keywords:'restaurant'},
{id:'a1_23',level:'A1',title:'Транспорт и путешествия',theory:'by bus/train/car/plane/bike. on foot. check-in, boarding pass, luggage.',practice:'Опиши маршрут.',memory:'by = на транспорте.',keywords:'transport'},
{id:'a1_24',level:'A1',title:'Дом и квартира',theory:'living room, bedroom, kitchen, bathroom. sofa, bed, table, chair.',practice:'Опиши квартиру.',memory:'Группируй по комнатам.',keywords:'home'},
{id:'a1_25',level:'A1',title:'Итог A1 + тест памяти',theory:'**Ты знаешь:** алфавит, числа, семью, еду, to be, Present Simple, артикли.\n\n**Тест:** 12 месяцев, 7 дней, 10 цветов, 5 профессий, 10 продуктов.',practice:'Рассказ о себе 15 предложений.',memory:'Повтори A1 за 25 минут.',keywords:'review A1'},

/* ============ A2 = 25 УРОКОВ ============ */
{id:'a2_01',level:'A2',title:'Past Simple — правильные',theory:'**V+ed.** live→lived. stop→stopped. study→studied.\n\n**Отрицание:** didn\'t + V1. **Вопрос:** Did you work?',practice:'10 предложений о вчера.',memory:'-ed = сделал в прошлом.',keywords:'past simple'},
{id:'a2_02',level:'A2',title:'Past Simple — неправильные',theory:'**Топ-30:** be→was/were, have→had, go→went, get→got, make→made, take→took, see→saw, know→knew, think→thought, say→said.',practice:'10 неправильных глаголов.',memory:'Группируй по паттернам.',keywords:'irregular'},
{id:'a2_03',level:'A2',title:'Past Continuous',theory:'**was/were + V-ing.** I was reading when he came.\n\nWhile I was cooking, she was watching TV.',practice:'Что делал в 8 вечера?',memory:'was/were + -ing = был в процессе.',keywords:'past continuous'},
{id:'a2_04',level:'A2',title:'Future — will / going to',theory:'**Will** — решения. **Going to** — планы.\n\nI will call. I\'m going to travel.',practice:'5 планов.',memory:'Will = спонтанно.',keywords:'future'},
{id:'a2_05',level:'A2',title:'Степени сравнения',theory:'**-er/-est** для коротких. **more/most** для длинных.\n\n**Исключения:** good→better→best, bad→worse→worst.',practice:'Сравни 5 пар.',memory:'Визуализируй: маленький→больше.',keywords:'comparatives'},
{id:'a2_06',level:'A2',title:'Some / Any / No',theory:'**Some** утверждения. **Any** вопросы/отрицания. **No** нет совсем.\n\nsomebody, something, anywhere, nobody.',practice:'10 предложений.',memory:'some=есть, any=?',keywords:'some any'},
{id:'a2_07',level:'A2',title:'Much / Many / A lot of',theory:'**Many** с исчисляемыми. **Much** с неисчисляемыми. **A lot of** универсально.\n\nfew/little vs a few/a little.',practice:'10 предложений.',memory:'Many = считаем.',keywords:'quantifiers'},
{id:'a2_08',level:'A2',title:'Present Perfect',theory:'**have/has + V3.**\n\n**Когда:** результат сейчас, опыт, незаконченный период.\n\nI have lost my keys. I have been to London.',practice:'10 предложений.',memory:'have + V3 = имею результат.',keywords:'present perfect'},
{id:'a2_09',level:'A2',title:'For / Since / Ago',theory:'**For** длительность. **Since** точка отсчёта. **Ago** назад.',practice:'5 предложений.',memory:'for=сколько, since=с какого.',keywords:'for since'},
{id:'a2_10',level:'A2',title:'Модальные must / have to / should',theory:'**Must** обязанность. **Have to** вынужден. **Should** совет.\n\n**Mustn\'t** запрет. **Don\'t have to** не обязан.',practice:'5 советов.',memory:'Must = сам решил.',keywords:'modals'},
{id:'a2_11',level:'A2',title:'Would like / Would love',theory:'**Would like** вежливое "хочу". I would like a coffee.',practice:'Заказ в ресторане.',memory:'would like = хотел бы.',keywords:'would like'},
{id:'a2_12',level:'A2',title:'Present Continuous vs Simple',theory:'**Simple** привычки. **Continuous** сейчас.\n\n**Не в Continuous:** like, love, hate, want, need, know.',practice:'10 предложений.',memory:'Simple=всегда, Continuous=сейчас.',keywords:'simple vs continuous'},
{id:'a2_13',level:'A2',title:'Условные 1 типа',theory:'**If + Present Simple, will + V.**\n\nIf it rains, I will stay home. **Не will после if!**',practice:'5 предложений.',memory:'If = условие.',keywords:'conditionals 1'},
{id:'a2_14',level:'A2',title:'Условные 2 типа',theory:'**If + Past Simple, would + V.**\n\nIf I had money, I would travel. If I were you...',practice:'5 мечт.',memory:'2 тип = мечта.',keywords:'conditionals 2'},
{id:'a2_15',level:'A2',title:'Прямая и косвенная речь',theory:'He said, "I am tired." → He said he was tired.\n\n**Сдвиг:** Present→Past, will→would, can→could.',practice:'5 предложений.',memory:'Косвенная = сдвиг на шаг.',keywords:'reported speech'},
{id:'a2_16',level:'A2',title:'Пассивный залог',theory:'**Present:** am/is/are + V3. **Past:** was/were + V3.\n\nThe book is written by Tolkien.',practice:'10 предложений.',memory:'be + V3 = пассив.',keywords:'passive'},
{id:'a2_17',level:'A2',title:'Вопросы — все типы',theory:'**Общий:** Do/Does/Did + S + V? **Специальный:** Wh- + вспом. + S + V.\n\n**К подлежащему:** Who came? (без do!)',practice:'10 вопросов.',memory:'Вопрос = вспом. вперёд.',keywords:'questions'},
{id:'a2_18',level:'A2',title:'Tag questions',theory:'Утверждение + отрицательный хвост.\n\nYou are a student, aren\'t you? She likes tea, doesn\'t she?',practice:'10 хвостов.',memory:'Хвост = противоположность.',keywords:'tag questions'},
{id:'a2_19',level:'A2',title:'Фразовые глаголы 1',theory:'get up, wake up, go on, come back, look for, look after, put on, take off, turn on/off, give up, find out, carry on, set up, put off, run out of.',practice:'10 предложений.',memory:'Группируй по частице.',keywords:'phrasal verbs 1'},
{id:'a2_20',level:'A2',title:'Фразовые глаголы 2',theory:'get along, break down, give back, look forward to, take care of, come up with, put up with, get away with, make up, look up, turn out, work out, hang out, figure out, point out.',practice:'10 предложений.',memory:'look forward to = ждать с радостью.',keywords:'phrasal verbs 2'},
{id:'a2_21',level:'A2',title:'Идиомы 1',theory:'Break a leg! Piece of cake. Hit the books. Under the weather. Once in a blue moon. Cost an arm and a leg.',practice:'10 идиом в диалоге.',memory:'Визуализируй образ.',keywords:'idioms 1'},
{id:'a2_22',level:'A2',title:'Идиомы 2',theory:'The ball is in your court. Burn the midnight oil. Blessing in disguise. Get cold feet. Raining cats and dogs. Break the ice.',practice:'5 идиом.',memory:'Визуализируй.',keywords:'idioms 2'},
{id:'a2_23',level:'A2',title:'Formal vs Informal',theory:'**Informal:** Hi! What\'s up? **Formal:** Dear Sir, I am writing to...\n\nВыбор зависит от ситуации.',practice:'2 версии письма.',memory:'Formal=галстук.',keywords:'formal informal'},
{id:'a2_24',level:'A2',title:'Чтение и аудирование',theory:'**Skimming** общее. **Scanning** конкретное. **Detailed** глубоко.\n\nАудирование: 6 Minute English, shadowing.',practice:'5 главных мыслей.',memory:'Skim = снять сливки.',keywords:'reading listening'},
{id:'a2_25',level:'A2',title:'Итог A2 + тест IQ',theory:'**Ты знаешь:** Past Simple, Continuous, Future, Present Perfect, модальные, условные 1-2, пассив.',practice:'Рассказ о отпуске 15-20 предложений.',memory:'Повтори A2 за 30 минут.',keywords:'review A2'},

/* ============ B1 = 25 УРОКОВ ============ */
{id:'b1_01',level:'B1',title:'Present Perfect Continuous',theory:'**have/has been + V-ing.**\n\nI have been working here for 5 years.\n\n**Отличие:** I have worked (завершено) vs I have been working (продолжается).',practice:'10 предложений.',memory:'have been + -ing = делаю и продолжаю.',keywords:'present perfect continuous'},
{id:'b1_02',level:'B1',title:'Past Perfect',theory:'**had + V3.**\n\nI had already eaten when he came.\n\nWhen I arrived, they had left.',practice:'5 историй.',memory:'had + V3 = уже было сделано до.',keywords:'past perfect'},
{id:'b1_03',level:'B1',title:'Past Perfect Continuous',theory:'**had been + V-ing.**\n\nShe had been working for 8 hours when she fell asleep.',practice:'5 предложений.',memory:'had been + -ing = делал какое-то время до.',keywords:'past perfect continuous'},
{id:'b1_04',level:'B1',title:'Future Continuous',theory:'**will be + V-ing.**\n\nAt 8 PM, I will be watching TV.',practice:'5 предложений.',memory:'will be + -ing = буду делать в момент.',keywords:'future continuous'},
{id:'b1_05',level:'B1',title:'Future Perfect',theory:'**will have + V3.**\n\nBy 2030, I will have finished university.',practice:'5 предложений.',memory:'will have + V3 = сделаю к тому времени.',keywords:'future perfect'},
{id:'b1_06',level:'B1',title:'Модальные — вероятность',theory:'**Must** 90%. **Might/May** 50%. **Can\'t** 0%.\n\n**Past:** must have + V3.',practice:'10 предположений.',memory:'Must=уверен, Might=сомневаюсь.',keywords:'modals probability'},
{id:'b1_07',level:'B1',title:'Used to / Would / Be used to',theory:'**Used to** привычка в прошлом. **Be used to** привык. **Would** повторяющееся.',practice:'5 предложений.',memory:'used to = раньше делал.',keywords:'used to'},
{id:'b1_08',level:'B1',title:'Условные 3 типа',theory:'**If + Past Perfect, would have + V3.**\n\nIf I had studied harder, I would have passed.',practice:'5 сожалений.',memory:'3 тип = сожаление.',keywords:'conditionals 3'},
{id:'b1_09',level:'B1',title:'Wish / If only',theory:'**Wish + Past Simple** настоящее. **Wish + Past Perfect** прошлое. **Wish + would** раздражение.',practice:'10 желаний.',memory:'wish = хотел бы, но нет.',keywords:'wish'},
{id:'b1_10',level:'B1',title:'Косвенная речь — сложная',theory:'He asked me where I lived. He told me to come.\n\n**Сдвиг:** now→then, today→that day.',practice:'10 предложений.',memory:'Косвенная = пересказ.',keywords:'reported speech advanced'},
{id:'b1_11',level:'B1',title:'Relative clauses',theory:'**who** люди. **which** вещи. **that** универсально. **where** места. **whose** принадлежность.',practice:'5 предложений.',memory:'who=человек, which=вещь.',keywords:'relative clauses'},
{id:'b1_12',level:'B1',title:'Gerund vs Infinitive',theory:'**Gerund (V-ing)** после предлогов, like, enjoy, mind, finish.\n\n**Infinitive (to V)** после want, need, decide, hope.',practice:'10 предложений.',memory:'Gerund=процесс, Infinitive=цель.',keywords:'gerund infinitive'},
{id:'b1_13',level:'B1',title:'Passive advanced',theory:'**Модальные в пассиве:** must be done. **Perfect:** has been built. **Continuous:** is being built.',practice:'10 предложений.',memory:'be + V3 = пассив.',keywords:'passive advanced'},
{id:'b1_14',level:'B1',title:'Tag questions advanced',theory:'Интонация ↘ уверен, ↗ спрашиваю. Let\'s go, shall we? I am right, aren\'t I?',practice:'10 хвостов.',memory:'Хвост = противоположность.',keywords:'tag advanced'},
{id:'b1_15',level:'B1',title:'Emphasis — do/does/did',theory:'I do love you. He does work hard. I did call you!\n\nNever have I seen such a thing.',practice:'5 эмфатических.',memory:'do/does/did = действительно.',keywords:'emphasis'},
{id:'b1_16',level:'B1',title:'Деловой английский — email',theory:'**Структура:** Subject, Salutation, Opening, Body, Closing, Signature.\n\nPlease find attached..., Looking forward to hearing from you.',practice:'Email 100 слов.',memory:'Email = структура.',keywords:'business email'},
{id:'b1_17',level:'B1',title:'Деловой английский — звонок',theory:'Good morning, this is... Could I speak to...? Could you repeat, please?',practice:'10 реплик.',memory:'Звонок = приветствие + цель.',keywords:'business call'},
{id:'b1_18',level:'B1',title:'Презентации — структура',theory:'Greeting, Topic, Outline, Body, Conclusion, Q&A.\n\n**Power phrases:** Imagine..., The key point is...',practice:'3-минутная презентация.',memory:'Презентация = крючок + структура.',keywords:'presentations'},
{id:'b1_19',level:'B1',title:'Интервью на работу',theory:'Tell me about yourself. Why this job? Strengths/weaknesses.\n\n**STAR:** Situation, Task, Action, Result.',practice:'5 вопросов.',memory:'STAR = 4 шага.',keywords:'interview'},
{id:'b1_20',level:'B1',title:'Идиомы деловые',theory:'Touch base, circle back, think outside the box, get the ball rolling, on the same page, low-hanging fruit, win-win.',practice:'5 идиом.',memory:'Визуализируй офис.',keywords:'business idioms'},
{id:'b1_21',level:'B1',title:'Сокращения и сленг',theory:'ASAP, FYI, BTW, IMO, BRB, LOL, OMG, TBH, IDK.\n\nСленг: chill, cool, awesome, hang out, no worries.',practice:'10 сообщений.',memory:'Сокращения = первые буквы.',keywords:'abbreviations'},
{id:'b1_22',level:'B1',title:'Collocations',theory:'**Make:** decision, mistake, money, coffee. **Do:** homework, sports.\n\n**Take:** break, shower. **Have:** breakfast, fun.',practice:'20 коллокаций.',memory:'Make=создавать, Do=выполнять.',keywords:'collocations'},
{id:'b1_23',level:'B1',title:'Word formation',theory:'**Suffixes:** -tion, -ment, -ness, -ity, -er.\n\n**Prefixes:** un-, dis-, re-, pre-, mis-.',practice:'30 слов.',memory:'Prefix=значение, Suffix=часть речи.',keywords:'word formation'},
{id:'b1_24',level:'B1',title:'Чтение и анализ',theory:'Skimming, Scanning, Detailed. Cornell method, mind maps.',practice:'5 главных мыслей.',memory:'Skim=быстро, Scan=точно.',keywords:'reading analysis'},
{id:'b1_25',level:'B1',title:'Итог B1 + IQ',theory:'Уровень B1 — уверенное общение.\n\n**Тест:** 5 времён, 20 фразовых, 10 идиом, 10 коллокаций.',practice:'Эссе 200 слов.',memory:'Повтори B1 за 40 минут.',keywords:'review B1'},

/* ============ B2 = 25 УРОКОВ ============ */
{id:'b2_01',level:'B2',title:'Инверсия — продвинутая',theory:'Never have I seen. Rarely does he. Not only did she... Only then did I understand.\n\nNo sooner had I arrived than...',practice:'10 инверсий.',memory:'Инверсия = вспом. вперёд.',keywords:'inversion'},
{id:'b2_02',level:'B2',title:'Смешанные условные',theory:'If I had studied medicine, I would be a doctor now.\n\nIf I were rich, I would have bought that house.',practice:'5 условных.',memory:'Смешанные = прошлое→настоящее.',keywords:'mixed conditionals'},
{id:'b2_03',level:'B2',title:'Cleft sentences',theory:'**It-cleft:** It was John who broke the window.\n\n**What-cleft:** What I need is a holiday.',practice:'10 cleft.',memory:'Cleft = фокус на элементе.',keywords:'cleft'},
{id:'b2_04',level:'B2',title:'Subjunctive',theory:'I suggest that he be present. It is essential that she arrive on time.\n\n**После:** suggest, recommend, demand, insist.',practice:'10 предложений.',memory:'Subjunctive = форма without -s.',keywords:'subjunctive'},
{id:'b2_05',level:'B2',title:'Фразовые глаголы продвинутые',theory:'put up with, come up with, look down on, get away with, do away with, make up for, take up, turn down, bring about.',practice:'10 предложений.',memory:'Группируй по частице.',keywords:'phrasal advanced'},
{id:'b2_06',level:'B2',title:'Идиомы B2',theory:'Bite the bullet, beat around the bush, cut corners, hit the nail on the head, pull someone\'s leg, sit on the fence, throw in the towel.',practice:'10 идиом.',memory:'Визуализируй образ.',keywords:'idioms B2'},
{id:'b2_07',level:'B2',title:'Discourse markers',theory:'**Добавление:** moreover, furthermore. **Контраст:** however, nevertheless. **Следствие:** therefore, consequently.',practice:'Эссе с 10 маркерами.',memory:'Связки = дорожные знаки.',keywords:'discourse'},
{id:'b2_08',level:'B2',title:'Формальная vs академическая речь',theory:'**Неформально:** get, a lot of, kids. **Формально:** obtain, numerous, children.\n\n**Хеджирование:** It could be argued.',practice:'10 предложений.',memory:'Академический = отстранённость.',keywords:'academic'},
{id:'b2_09',level:'B2',title:'Аргументация',theory:'Claim, Evidence, Warrant, Rebuttal, Conclusion.\n\nIt is widely believed that..., Conversely, critics argue...',practice:'Аргумент за/против.',memory:'Аргумент = тезис + доказательство.',keywords:'argumentation'},
{id:'b2_10',level:'B2',title:'Публичные выступления',theory:'Hook + Story + Point + Call to action.\n\n**Приёмы:** rule of three, repetition, pause.',practice:'Речь 5 минут.',memory:'Речь = история + эмоция.',keywords:'public speaking'},
{id:'b2_11',level:'B2',title:'Переговоры',theory:'BATNA. What if we... Let\'s find a middle ground.\n\n**Тактики:** anchoring, framing, silence.',practice:'Разыграй переговоры.',memory:'BATNA = план Б.',keywords:'negotiation'},
{id:'b2_12',level:'B2',title:'Дебаты',theory:'Opening, Arguments, Rebuttal, Closing.\n\nI strongly believe..., On the contrary...',practice:'Дебаты 5 минут.',memory:'Дебаты = тезис + опровержение.',keywords:'debate'},
{id:'b2_13',level:'B2',title:'Идиомы в контексте',theory:'Once in a blue moon. Bury the hatchet. See eye to eye. A blessing in disguise. The last straw.',practice:'Диалог с 5 идиомами.',memory:'Визуализируй.',keywords:'idioms context'},
{id:'b2_14',level:'B2',title:'Интервью на работу B2',theory:'Tell me about a time when... How do you handle...\n\n**STAR:** Situation, Task, Action, Result.',practice:'5 STAR-вопросов.',memory:'STAR = 4 шага.',keywords:'behavioral'},
{id:'b2_15',level:'B2',title:'Рецензия / обзор',theory:'Introduction, Summary, Analysis, Evaluation, Recommendation.',practice:'Рецензия 200 слов.',memory:'Рецензия = описание + анализ.',keywords:'review'},
{id:'b2_16',level:'B2',title:'Научная статья — структура',theory:'Abstract, Intro, Methods, Results, Discussion, Conclusion.\n\nThis paper examines..., The findings suggest...',practice:'Abstract 100 слов.',memory:'IMRaD.',keywords:'scientific'},
{id:'b2_17',level:'B2',title:'Разговорный B2',theory:'Well, you know, I mean, actually. I\'m thrilled, I\'m fed up.\n\nI see your point, but...',practice:'Диалог с 10 фразами.',memory:'Разговорный = естественность.',keywords:'conversational'},
{id:'b2_18',level:'B2',title:'Нюансы тона',theory:'**Вежливо:** Could you possibly...? **Нейтрально:** Can you...? **Прямо:** Do it.',practice:'Одна просьба — 5 тонов.',memory:'Тон = отношение.',keywords:'tone'},
{id:'b2_19',level:'B2',title:'Collocations B2',theory:'Take measures. Draw a conclusion. Meet a deadline. Raise awareness. Reach an agreement. Bridge the gap.',practice:'20 коллокаций.',memory:'Коллокации = устойчивые пары.',keywords:'collocations B2'},
{id:'b2_20',level:'B2',title:'Narrative tenses',theory:'Past Simple, Past Continuous, Past Perfect, Past Perfect Continuous.\n\nI was walking home when I saw him.',practice:'История 200 слов.',memory:'Рассказ = фон + событие.',keywords:'narrative'},
{id:'b2_21',level:'B2',title:'Ellipsis & Substitution',theory:'— Would you like tea? — I\'d love to. The blue one. The one I told you about.',practice:'10 предложений.',memory:'Эллипсис = пропуск очевидного.',keywords:'ellipsis'},
{id:'b2_22',level:'B2',title:'Idiomatic expressions B2',theory:'Break the ice. Bend over backwards. Go the extra mile. Bite off more than you can chew.',practice:'5 диалогов.',memory:'Визуализируй.',keywords:'idiomatic B2'},
{id:'b2_23',level:'B2',title:'Advanced phrasal verbs',theory:'Account for, bring about, carry out, come down to, end up, figure out, point out, sort out.',practice:'10 предложений.',memory:'Группируй по значению.',keywords:'advanced phrasal'},
{id:'b2_24',level:'B2',title:'Формальные письма',theory:'**Complaint:** Dear Sir/Madam, I am writing to complain... **Application:** I am writing to apply for...',practice:'3 письма.',memory:'Формальное = структура.',keywords:'formal letters'},
{id:'b2_25',level:'B2',title:'Итог B2 + IQ',theory:'Уровень B2 — сложные тексты, абстрактные темы.',practice:'Эссе 300 слов.',memory:'Повтори B2 за 50 минут.',keywords:'review B2'},

/* ============ C1 = 25 УРОКОВ ============ */
{id:'c1_01',level:'C1',title:'Nuances of meaning',theory:'house/home/dwelling. smart/intelligent/clever. thin/skinny/slim.\n\ncheap/inexpensive/affordable.',practice:'10 пар слов.',memory:'Коннотация = окраска.',keywords:'nuance'},
{id:'c1_02',level:'C1',title:'Idioms C1',theory:'It takes two to tango. To be on the fence. Throw someone under the bus. Play devil\'s advocate. Take it with a grain of salt.',practice:'10 идиом.',memory:'Визуализируй.',keywords:'idioms C1'},
{id:'c1_03',level:'C1',title:'Academic writing — hedging',theory:'It could be argued that... There is evidence to suggest... It appears to be...\n\n**Avoid:** I think, very, really.',practice:'Абзац с hedging.',memory:'Hedging = осторожность.',keywords:'academic writing'},
{id:'c1_04',level:'C1',title:'Literary devices',theory:'Metaphor, simile, personification, alliteration, hyperbole, oxymoron.',practice:'5 предложений.',memory:'Приёмы = украшения.',keywords:'literary devices'},
{id:'c1_05',level:'C1',title:'Register',theory:'Frozen, Formal, Consultative, Casual, Intimate.\n\n**Mixing регистров = ошибка.**',practice:'Одна тема — 5 регистров.',memory:'Регистр = одежда для речи.',keywords:'register'},
{id:'c1_06',level:'C1',title:'Сочинение-рассуждение',theory:'Intro + тезис. Аргумент 1 + пример. Аргумент 2. Контраргумент. Заключение.\n\n400-500 слов.',practice:'Сочинение 400 слов.',memory:'Сочинение = тезис + аргументы.',keywords:'essay'},
{id:'c1_07',level:'C1',title:'Стилистические приёмы',theory:'Anaphora, chiasmus, antithesis, rhetorical question.',practice:'5 предложений.',memory:'Визуализируй речь.',keywords:'stylistic'},
{id:'c1_08',level:'C1',title:'Дебаты C1',theory:'Position, Evidence, Rebuttal, Cross-examination, Closing.\n\nI take issue with..., I beg to differ.',practice:'Дебаты 10 минут.',memory:'Дебаты = позиция + опровержение.',keywords:'debate C1'},
{id:'c1_09',level:'C1',title:'Публичная речь',theory:'Hook + Story + Point + Call to action. Rule of three, repetition, pause.',practice:'Речь 5 минут.',memory:'Речь = история + действие.',keywords:'public speech'},
{id:'c1_10',level:'C1',title:'Юмор на английском',theory:'Puns, irony, sarcasm, deadpan, self-deprecating.\n\n**Безопасно:** self-deprecating, observational.',practice:'5 шуток.',memory:'Юмор = неожиданность.',keywords:'humor'},
{id:'c1_11',level:'C1',title:'Cleft & Inversion advanced',theory:'I do apologize. Off went the alarm. Under no circumstances will I agree.',practice:'10 предложений.',memory:'Инверсия = переворот.',keywords:'cleft inversion'},
{id:'c1_12',level:'C1',title:'Cohesion',theory:'Reference, Substitution, Ellipsis, Conjunction, Lexical cohesion.\n\nThe company launched a product. This was a success.',practice:'Выдели связки.',memory:'Cohesion = клей текста.',keywords:'cohesion'},
{id:'c1_13',level:'C1',title:'Coherence',theory:'Topic sentence, Supporting, Example, Concluding.\n\nFirst..., Second..., Finally...',practice:'Перепиши текст.',memory:'Coherence = логика.',keywords:'coherence'},
{id:'c1_14',level:'C1',title:'Критическое мышление',theory:'What is the claim? What is the evidence? Is the reasoning valid? Counterarguments? Conclusion?',practice:'Анализ статьи.',memory:'Критическое = вопросы.',keywords:'critical thinking'},
{id:'c1_15',level:'C1',title:'Сложные тексты',theory:'Skim, Scan, Close reading. Cornell method, mind maps.',practice:'Mind map.',memory:'Визуализируй структуру.',keywords:'complex texts'},
{id:'c1_16',level:'C1',title:'Литературный анализ',theory:'Theme, Character, Plot, Setting, Point of view, Symbolism.',practice:'Анализ рассказа.',memory:'Анализ = элементы + связи.',keywords:'literary analysis'},
{id:'c1_17',level:'C1',title:'Научный стиль',theory:'Passive voice, Nominalization, Precise vocabulary, Citations.\n\nIt has been demonstrated that...',practice:'Научный abstract.',memory:'Научный = отстранённость.',keywords:'scientific style'},
{id:'c1_18',level:'C1',title:'Юридический английский',theory:'Plaintiff, defendant, contract, tort, damages.\n\nhereby, thereto, notwithstanding.',practice:'10 терминов.',memory:'Юридический = точность.',keywords:'legal English'},
{id:'c1_19',level:'C1',title:'Медицинский английский',theory:'Diagnosis, symptoms, treatment, prescription.\n\nThe patient presents with...',practice:'Отчёт 200 слов.',memory:'Медицинский = точность.',keywords:'medical English'},
{id:'c1_20',level:'C1',title:'IT-английский',theory:'API, deployment, scalability, latency.\n\nWe need to optimize... The system is down. Let\'s roll back.',practice:'Описание 200 слов.',memory:'IT = точность + краткость.',keywords:'IT English'},
{id:'c1_21',level:'C1',title:'Бизнес-презентация',theory:'Hook, Problem, Solution, Market, Team, Traction, Ask.\n\nPitch 3-5 минут.',practice:'Питч стартапа.',memory:'Питч = проблема + решение.',keywords:'business pitch'},
{id:'c1_22',level:'C1',title:'Переговоры C1',theory:'Anchoring, Framing, BATNA, MESO, Silence.',practice:'Сложные переговоры.',memory:'Переговоры = подготовка + тактика.',keywords:'negotiation C1'},
{id:'c1_23',level:'C1',title:'Медиация',theory:'Intro, Issues, Interests, Options, Agreement.\n\nLet\'s find common ground..., I hear you saying...',practice:'Медиация конфликта.',memory:'Медиация = слушание + решение.',keywords:'mediation'},
{id:'c1_24',level:'C1',title:'Философия языка',theory:'Sapir-Whorf, Wittgenstein, Chomsky, Austin.\n\nLanguage shapes thought.',practice:'Эссе 400 слов.',memory:'Философия = вопросы.',keywords:'philosophy'},
{id:'c1_25',level:'C1',title:'Итог C1 + IQ',theory:'Уровень C1 — свободное владение, тонкие нюансы.',practice:'Эссе 500 слов.',memory:'Повтори C1 за 60 минут.',keywords:'review C1'}
];

var MEMORY_MODULE=[
{id:'mem_01',level:'Memory',title:'Как работает память',theory:'**3 типа памяти:** сенсорная (0.5-3 сек), краткосрочная (15-30 сек, 7±2), долгосрочная (неограниченно).\n\n**Кривая Эббингауза:** 20 мин → 58% забыто, 1 день → 67%, 1 неделя → 75%.\n\n**Вывод:** повторяй через 1ч, 1д, 3д, 7д, 30д.',practice:'Составь расписание повторений на неделю для 10 новых слов.',memory:'Кривая Эббингауза = обрыв вниз.',keywords:'memory, Ebbinghaus'},
{id:'mem_02',level:'Memory',title:'Метод локусов',theory:'1. Выбери знакомое место. 2. Определи 10 точек. 3. Размести образы. 4. Пройди маршрут.',practice:'Размести 10 английских слов в квартире.',memory:'Локусы = места.',keywords:'method of loci'},
{id:'mem_03',level:'Memory',title:'Мнемоника',theory:'Акроним, акростих, рифма, история, числа-образы.',practice:'Мнемонику для 10 слов.',memory:'Мнемоника = крючок.',keywords:'mnemonics'},
{id:'mem_04',level:'Memory',title:'Интервальное повторение (Anki)',theory:'1 день → 3 → 7 → 14 → 30 → 60 → 120.\n\n**Правило:** 20 мин в день лучше 3 часов раз в неделю.',practice:'20 карточек Anki.',memory:'Anki = умное повторение.',keywords:'spaced repetition'},
{id:'mem_05',level:'Memory',title:'Чанкинг',theory:'Краткосрочная память 7±2. Группируй → больше.\n\n917-555-1234 (3 чанка).',practice:'30 слов в 6 чанков.',memory:'Chunk = кусок.',keywords:'chunking'},
{id:'mem_06',level:'Memory',title:'Активное припоминание',theory:'Testing effect: попытка вспомнить сильнее перечитывания.\n\n70% припоминание, 30% чтение.',practice:'Закрой урок. Напиши по памяти.',memory:'Recall > Recognition.',keywords:'active recall'},
{id:'mem_07',level:'Memory',title:'Метод Фейнмана',theory:'1. Выбери концепт. 2. Объясни 12-летнему. 3. Найди пробелы. 4. Упрости.',practice:'Объясни 3 темы простыми словами.',memory:'Если не можешь объяснить — не понял.',keywords:'Feynman'},
{id:'mem_08',level:'Memory',title:'Сон и память',theory:'Медленный сон — факты. REM — эмоции, навыки. 7-9 часов.\n\nУчи перед сном, повторяй утром.',practice:'Учи 10 слов перед сном.',memory:'Сон = сохранение.',keywords:'sleep, memory'},
{id:'mem_09',level:'Memory',title:'Двойное кодирование',theory:'Paivio: мозг запоминает лучше со словами + образами.\n\nСлово + картинка. Текст + схема.',practice:'Mind map по 3 урокам.',memory:'Слово + образ = двойной след.',keywords:'dual coding'},
{id:'mem_10',level:'Memory',title:'Итог: система памяти',theory:'1. Учи активно. 2. Повторяй интервально. 3. Локусы. 4. Мнемоники. 5. Чанкинг. 6. Спи 7-9. 7. Учи перед сном.\n\n**Результат:** память ×3-5 за месяц.',practice:'Составь личную систему.',memory:'Система > мотивация.',keywords:'memory system'}
];

var IQ_MODULE=[
{id:'iq_01',level:'IQ',title:'Что такое IQ',theory:'Средний 100, σ = 15.\n\n**Компоненты:** логика, пространственное, вербальное, рабочая память, скорость.',practice:'Пройди тест IQ Равена.',memory:'IQ тренируется.',keywords:'IQ'},
{id:'iq_02',level:'IQ',title:'Логические последовательности',theory:'Арифметические: 2,4,6,8. Геометрические: 2,4,8,16. Фибоначчи: 1,1,2,3,5,8.',practice:'1,4,9,16,? / 2,6,12,20,? / 1,1,2,3,5,? / 3,6,12,24,?',memory:'Ищи паттерн: +, ×.',keywords:'logic sequences'},
{id:'iq_03',level:'IQ',title:'Аналогии',theory:'A:B = C:? Часть-целое, противоположность, функция, категория.',practice:'книга:читать = нож:? / кот:мяукать = собака:? / рука:перчатка = нога:?',memory:'Аналогия = связь.',keywords:'analogies'},
{id:'iq_04',level:'IQ',title:'Пространственное мышление',theory:'Вращение фигур, развёртки куба, танграм, тетрис, шахматы.',practice:'Развёртка куба + 5 задач.',memory:'Правое полушарие.',keywords:'spatial'},
{id:'iq_05',level:'IQ',title:'Рабочая память',theory:'4±1 чанка. N-back, двойная задача, обратный счёт.',practice:'N-back 10 мин/день.',memory:'Рабочая память = RAM.',keywords:'working memory'},
{id:'iq_06',level:'IQ',title:'Скорочтение',theory:'Средняя 200-250 слов/мин. Цель 400-600.\n\nУбрать субвокализацию, читать блоками, указка, без регрессий.',practice:'10 минут с указкой.',memory:'Глаза двигаются скачками.',keywords:'speed reading'},
{id:'iq_07',level:'IQ',title:'Критическое мышление',theory:'5 вопросов: кто, что, доказательства, альтернативы, если ошибается.\n\nЛовушки: confirmation bias, ad hominem, straw man.',practice:'Анализ новости.',memory:'Критическое = вопросы.',keywords:'critical thinking'},
{id:'iq_08',level:'IQ',title:'Математическое мышление',theory:'Ментальная арифметика, оценка, проценты, вероятность.\n\n17×23 = (20-3)(20+3) = 400-9 = 391.',practice:'20 примеров в уме.',memory:'Математика = паттерны.',keywords:'math'},
{id:'iq_09',level:'IQ',title:'Шахматы и стратегия',theory:'Контроль центра, развитие фигур, безопасность короля, тактика: вилка, связка, мат.',practice:'1 партия в день + 5 задач.',memory:'Шахматы = IQ-спорт.',keywords:'chess'},
{id:'iq_10',level:'IQ',title:'Итог: IQ-система',theory:'10 мин N-back + 5 задач + 1 партия + 10 мин скорочтения.\n\n**Через 3 месяца:** IQ +10-15.',practice:'Расписание на неделю.',memory:'IQ тренируется как мышца.',keywords:'IQ system'}
];

var EQ_MODULE=[
{id:'eq_01',level:'EQ',title:'Что такое EQ',theory:'Гоулман: 1. Самосознание. 2. Саморегуляция. 3. Мотивация. 4. Эмпатия. 5. Социальные навыки.\n\n**EQ важнее IQ в 2 раза.**',practice:'Оцени EQ по 5 компонентам.',memory:'EQ = 5 компонентов.',keywords:'EQ'},
{id:'eq_02',level:'EQ',title:'Самосознание',theory:'Дневник эмоций. Назови эмоцию (name it to tame it). Шкала 1-10.\n\n"Я чувствую тревогу 7/10, триггер — дедлайн."',practice:'Дневник 7 дней.',memory:'Назови = укроти.',keywords:'self-awareness'},
{id:'eq_03',level:'EQ',title:'Саморегуляция',theory:'Дыхание 4-7-8, пауза 6 секунд, переоценка, физическая активность, холодная вода.\n\n**Правило:** пауза между стимулом и реакцией.',practice:'Пауза 6 сек в конфликтах.',memory:'Пауза = свобода выбора.',keywords:'self-regulation'},
{id:'eq_04',level:'EQ',title:'Эмпатия',theory:'Когнитивная (понимаю), эмоциональная (чувствую), сострадательная (действую).\n\nСлушай без перебивания, парафраз.',practice:'3 разговора в активном слушании.',memory:'Эмпатия = встать на место.',keywords:'empathy'},
{id:'eq_05',level:'EQ',title:'Мотивация',theory:'Внутренняя vs внешняя. Деси/Райан: автономия, компетентность, связанность.',practice:'5 задач — внутренний смысл.',memory:'Внутренняя = топливо.',keywords:'motivation'},
{id:'eq_06',level:'EQ',title:'Социальные навыки',theory:'Я-сообщения, SBI (Situation-Behavior-Impact), ННО.',practice:'SBI 3 раза.',memory:'Социальные = навыки.',keywords:'social skills'},
{id:'eq_07',level:'EQ',title:'Управление стрессом',theory:'Box breathing, прогрессивная релаксация, визуализация, природа 2ч/нед, спорт.\n\nКортизол ↓, эндорфины ↑.',practice:'3 техники за неделю.',memory:'Стресс управляем.',keywords:'stress management'},
{id:'eq_08',level:'EQ',title:'Конфликты',theory:'Томас-Килманн: соперничество, избегание, компромисс, сотрудничество, приспособление.\n\n**Лучший:** сотрудничество.',practice:'3 конфликта по стилям.',memory:'Сотрудничество = 1+1=3.',keywords:'conflicts'},
{id:'eq_09',level:'EQ',title:'Границы',theory:'"Нет" без вины. "Мне нужно время". "Я не готов".\n\n**Формула:** "Я не могу X, но могу Y".',practice:'Скажи "нет" 3 раза.',memory:'Границы = уважение.',keywords:'boundaries'},
{id:'eq_10',level:'EQ',title:'Итог: EQ-система',theory:'Дневник + пауза + слушание + я-сообщение + медитация.\n\n**Через месяц:** EQ +20%.',practice:'EQ-расписание.',memory:'EQ = навык.',keywords:'EQ system'}
];

var FINANCE_MODULE=[
{id:'fin_01',level:'Finance',title:'Основы финансов',theory:'4 столпа: доход, расходы, сбережения, инвестиции.\n\n50/30/20. Подушка 3-6 мес.',practice:'Бюджет 50/30/20.',memory:'50/30/20 = карта.',keywords:'finance basics'},
{id:'fin_02',level:'Finance',title:'Учёт расходов',theory:'Приложения, Excel, конверты, правило 24 часов.\n\n**Записывай каждую трату.**',practice:'7 дней записей.',memory:'Учёт = контроль.',keywords:'budgeting'},
{id:'fin_03',level:'Finance',title:'Долги',theory:'Снежный ком (мелкий первый), лавина (высокий %). Минимум по всем, максимум по одному.',practice:'Список долгов + план.',memory:'Долг = минус.',keywords:'debt'},
{id:'fin_04',level:'Finance',title:'Инвестиции',theory:'Долгосрочно, диверсификация, индексные фонды, DCA.\n\n10% годовых → ×2 за 7 лет.',practice:'3 индексных фонда.',memory:'Инвестиции = время.',keywords:'investing'},
{id:'fin_05',level:'Finance',title:'FIRE',theory:'Норма сбережений 50%+, 25× расходов, 4% правило.',practice:'FIRE-число.',memory:'FIRE = свобода.',keywords:'FIRE'},
{id:'fin_06',level:'Finance',title:'Доход',theory:'Работа, фриланс, пассивный, инвестиции, бизнес.\n\n**Правило:** 3+ источника.',practice:'2 идеи доп. дохода.',memory:'Доход = множественный.',keywords:'income'},
{id:'fin_07',level:'Finance',title:'Налоги и вычеты',theory:'НДФЛ 13-15%, ИИС, вычеты (обучение, лечение), самозанятость 4-6%.',practice:'Какие вычеты доступны?',memory:'Налоги = оптимизируй.',keywords:'taxes'},
{id:'fin_08',level:'Finance',title:'Финансовые цели',theory:'SMART: Specific, Measurable, Achievable, Relevant, Time-bound.',practice:'3 цели по SMART.',memory:'Цель = цифра + срок.',keywords:'goals'},
{id:'fin_09',level:'Finance',title:'Психология денег',theory:'Импульсивные покупки, lifestyle inflation, FOMO.\n\nПравило 24 часов.',practice:'Правило 24 часов неделю.',memory:'Деньги = эмоции.',keywords:'money psychology'},
{id:'fin_10',level:'Finance',title:'Итог: система',theory:'Учёт + бюджет + подушка + долги + инвестиции + 3 источника + вычеты.\n\n**Через год:** +30% капитала.',practice:'Финплан на год.',memory:'Система > удача.',keywords:'finance system'}
];

var NEURO_MODULE=[
{id:'neuro_01',level:'Neuro',title:'Как учится мозг',theory:'Нейропластичность. Синапсы. "Fire together, wire together". Миелин ускоряет в 100 раз.',practice:'1 навык 30 дней.',memory:'Мозг = мышца.',keywords:'neuroplasticity'},
{id:'neuro_02',level:'Neuro',title:'Дофамин и мотивация',theory:'Дофамин = предвкушение. Соцсети → ямы.\n\nДофаминовое голодание, скука, награда после усилия.',practice:'Голодание 4 часа.',memory:'Дофамин = топливо.',keywords:'dopamine'},
{id:'neuro_03',level:'Neuro',title:'Сон и обучение',theory:'NREM — факты. REM — эмоции, креатив. 7-9 часов. Учи перед сном.',practice:'10 слов перед сном.',memory:'Сон = обучение.',keywords:'sleep learning'},
{id:'neuro_04',level:'Neuro',title:'Стресс и обучение',theory:'Оптимальный стресс → поток. Кортизол убивает нейроны гиппокампа.',practice:'Найди оптимум.',memory:'Стресс = дозируй.',keywords:'stress learning'},
{id:'neuro_05',level:'Neuro',title:'Питание для мозга',theory:'Omega-3, ягоды, тёмный шоколад, зелёный чай, яйца, куркума.\n\nИзбегать: сахар, трансжиры, алкоголь.',practice:'3 продукта в рацион.',memory:'Мозг = 60% жира.',keywords:'brain nutrition'},
{id:'neuro_06',level:'Neuro',title:'Физические упражнения',theory:'BDNF — "удобрение для мозга". 150 мин кардио + 2 силовые.',practice:'30 мин кардио перед учёбой.',memory:'Движение = мозг.',keywords:'exercise brain'},
{id:'neuro_07',level:'Neuro',title:'Медитация и мозг',theory:'Утолщение префронтальной коры. Уменьшение миндалины. 10-20 мин, 8 недель.',practice:'Медитация 8 недель.',memory:'Медитация = фитнес.',keywords:'meditation brain'},
{id:'neuro_08',level:'Neuro',title:'Внимание и фокус',theory:'Фокус, рассеянное, переключение. Стоимость переключения 23 минуты.',practice:'90 мин одна задача.',memory:'Фокус = валюта XXI века.',keywords:'attention focus'},
{id:'neuro_09',level:'Neuro',title:'Креативность',theory:'Default Mode Network активна в покое. Прогулка, душ, скука, смена обстановки.',practice:'Прогулка 30 мин.',memory:'Креатив = покой + опыт.',keywords:'creativity'},
{id:'neuro_10',level:'Neuro',title:'Итог: нейро-система',theory:'Сон 7-9 + спорт 150 + медитация 10 + питание + фокус 90 + дофамин-контроль + стресс.\n\n**Через 3 месяца:** мозг ×2.',practice:'Нейро-расписание.',memory:'Мозг = орган.',keywords:'neuro system'}
];

var ALL_LESSONS=ENGLISH_125.concat(MEMORY_MODULE,IQ_MODULE,EQ_MODULE,FINANCE_MODULE,NEURO_MODULE);
window.__ENGLISH_125=ENGLISH_125;
window.__ALL_LESSONS=ALL_LESSONS;
window.__MEMORY_MODULE=MEMORY_MODULE;
window.__IQ_MODULE=IQ_MODULE;
window.__EQ_MODULE=EQ_MODULE;
window.__FINANCE_MODULE=FINANCE_MODULE;
window.__NEURO_MODULE=NEURO_MODULE;