'use strict';
/* ENGLISH 125 LESSONS + 5 MODULES */

var ENGLISH_125=[
/* ============ A1 — 25 УРОКОВ ============ */
{id:'a1_01',level:'A1',title:'Алфавит, звуки и IPA',theory:'**26 букв, 44 звука.** Английский — не фонетический: "through" = /θruː/, "though" = /ðəʊ/.\n\n**Ключевые звуки IPA:**\n• /θ/ — think, three, thank\n• /ð/ — this, that, mother\n• /ŋ/ — sing, thing, long\n• /æ/ — cat, bad, apple\n• /ɪ/ vs /iː/ — ship vs sheep\n• /w/ vs /v/ — west vs vest\n\n**Правило:** гласная + согласная + e = долгий звук: make, bike, note.',practice:'Произнеси 10 пар: ship/sheep, bad/bed, cat/cut, west/vest, think/sink.',memory:'Мнемоника: /θ/ — язык между зубами, как "с" с шепелявостью. /ð/ — то же, но с голосом.',keywords:'alphabet IPA phonetics pronunciation'},
{id:'a1_02',level:'A1',title:'Приветствия и знакомство',theory:'**Формальные:** Good morning (до 12:00), Good afternoon (12-18), Good evening (после 18).\n\n**Неформальные:** Hi, Hey, What\'s up?, How\'s it going?\n\n**Диалог-шаблон:**\n— Hi! I\'m Alex. Nice to meet you.\n— Nice to meet you too. I\'m Maria.\n— Where are you from?\n— I\'m from Russia. And you?',practice:'Составь диалог знакомства с 5 репликами. Используй 3 разных приветствия.',memory:'Свяжи приветствие со временем: Morning→до 12, Afternoon→12-18, Evening→после 18.',keywords:'greetings introduce small talk'},
{id:'a1_03',level:'A1',title:'Числа 1-100 и даты',theory:'**1-12 запомнить:** one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve.\n\n**13-19 = -teen:** thirteen, fourteen...\n\n**Десятки = -ty:** twenty, thirty, **forty** (без u!), fifty, sixty.\n\n**Сотни:** one hundred, two hundred.\n\n**Даты:** on the 5th of May = May 5th.',practice:'Назови: 7, 13, 21, 45, 87, 100, 2024. Напиши свой день рождения.',memory:'13-19 = teen (подростки), 20-90 = ty (взрослые). ThirTEEN vs THIRty — ударение.',keywords:'numbers dates pronunciation'},
{id:'a1_04',level:'A1',title:'Цвета и оттенки',theory:'**Базовые:** red, blue, green, yellow, black, white, orange, pink, purple, brown, gray, gold, silver.\n\n**Оттенки:** light blue, dark green, bright red.\n\n**Идиомы:**\n• I feel blue — мне грустно\n• Green with envy — завидует\n• Out of the blue — неожиданно',practice:'Опиши 5 предметов вокруг. Составь 3 предложения с идиомами.',memory:'Цвета ассоциируй с эмоциями: blue=грусть, green=зависть, red=гнев.',keywords:'colors idioms adjectives'},
{id:'a1_05',level:'A1',title:'Семья и родственники',theory:'**Immediate:** mother/mom, father/dad, sister, brother, son, daughter.\n\n**Extended:** grandmother, grandfather, aunt, uncle, cousin, nephew, niece.\n\n**In-laws:** mother-in-law, brother-in-law.\n\n**Шаблон:** I have a mother, a father, and one sister.',practice:'Нарисуй семейное древо. Подпиши 10 родственников.',memory:'-in-law = "по закону" (через брак). Cousin = двоюродный.',keywords:'family relatives'},
{id:'a1_06',level:'A1',title:'Еда, напитки, ресторан',theory:'**Meals:** breakfast, lunch, dinner, snack.\n\n**Food:** bread, meat, fish, rice, pasta, egg, cheese.\n\n**Fruits:** apple, banana, orange, grape, strawberry.\n\n**Veggies:** potato, tomato, carrot, onion.\n\n**Drinks:** water, tea, coffee, juice, milk.',practice:'Составь меню на день. Разыграй заказ в кафе.',memory:'Группируй по категориям: фрукты, овощи, напитки.',keywords:'food restaurant ordering'},
{id:'a1_07',level:'A1',title:'Глагол to be — фундамент',theory:'**Формы:** am / is / are.\n\nI **am** → I\'m\nYou **are** → You\'re\nHe/She/It **is** → He\'s\nWe **are** → We\'re\nThey **are** → They\'re\n\n**Отрицание:** I am not / isn\'t / aren\'t.\n\n**Вопрос:** Am I? Is he? Are they?',practice:'10 предложений с разными подлежащими. Задай 5 вопросов.',memory:'Формула: I→am, He/She/It→is, You/We/They→are.',keywords:'to be present simple'},
{id:'a1_08',level:'A1',title:'Present Simple — привычки',theory:'**Формула:** Subject + V(s/es) + ...\n\nI work. You work. He work**s**. She work**s**.\n\n**Маркеры:** always, usually, often, sometimes, never, every day.\n\n**Пример:** I usually wake up at 7.',practice:'Напиши 10 предложений о своём дне.',memory:'He/She/It → +s (как "он" один — ему нужна "s").',keywords:'present simple habits'},
{id:'a1_09',level:'A1',title:'Артикли a/an/the',theory:'**a** — перед согласным звуком: a book, a university.\n**an** — перед гласным: an apple, an hour.\n**the** — конкретный предмет, единственный в мире.\n\n**Без артикля:** имена, города, страны (кроме the USA, the UK).',practice:'Вставь артикль: ___ cat, ___ orange, ___ sun, ___ Russia.',memory:'a/an = "один из многих". the = "тот самый".',keywords:'articles a an the'},
{id:'a1_10',level:'A1',title:'Множественное число',theory:'**Обычно:** +s (book → books).\n**После s, x, ch, sh:** +es (box → boxes).\n**Согласная + y:** y→ies (city → cities).\n**Исключения:** man→men, woman→women, child→children, foot→feet, tooth→teeth.',practice:'Образуй мн. число: cat, bus, story, child, foot, woman.',memory:'Исключения пой как рифму: man-men, woman-women, foot-feet.',keywords:'plurals irregular'},
{id:'a1_11',level:'A1',title:'This / That / These / Those',theory:'**this** — этот (близко, ед.)\n**that** — тот (далеко, ед.)\n**these** — эти (близко, мн.)\n**those** — те (далеко, мн.)\n\n**Пример:** This is my book. That is your car.',practice:'Опиши 5 предметов: This is... That is...',memory:'this/these — близко (здесь), that/those — далеко (там).',keywords:'demonstratives'},
{id:'a1_12',level:'A1',title:'Притяжательные и \'s',theory:'**Прилагательные:** my, your, his, her, its, our, their.\n**Местоимения:** mine, yours, his, hers, ours, theirs.\n\n**\'s** — принадлежность: John\'s car, my mother\'s house.',practice:'Опиши вещи: My bag, your phone, his car, her book.',memory:'my=мой, your=твой, his=его, her=её, our=наш, their=их.',keywords:'possessives'},
{id:'a1_13',level:'A1',title:'Предлоги места',theory:'**in** — внутри: in the box.\n**on** — на поверхности: on the table.\n**under** — под: under the bed.\n**next to** — рядом.\n**between** — между.\n**behind** — за.\n**in front of** — перед.',practice:'Опиши комнату: The book is on the table.',memory:'Визуализируй кота: on (на), in (в), under (под), behind (за).',keywords:'prepositions of place'},
{id:'a1_14',level:'A1',title:'Время и часы',theory:'**O\'clock** — ровно: 3:00 = three o\'clock.\n**Quarter past** — 15 после: 3:15 = quarter past three.\n**Half past** — 30: 3:30 = half past three.\n**Quarter to** — 15 до: 3:45 = quarter to four.\n\n**AM** (до полудня), **PM** (после).',practice:'Назови время: 7:00, 8:30, 9:15, 10:45, 12:00, 17:20.',memory:'past = "после", to = "до".',keywords:'time clock'},
{id:'a1_15',level:'A1',title:'Дни, месяцы, времена года',theory:'**Дни:** Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday.\n\n**Месяцы:** January, February, March, April, May, June, July, August, September, October, November, December.\n\n**Сезоны:** spring, summer, autumn/fall, winter.',practice:'Скажи свой день рождения: My birthday is on...',memory:'Дни: Mon-Sun. Месяцы: Jan-Dec.',keywords:'days months seasons'},
{id:'a1_16',level:'A1',title:'Can / Can\'t — умения',theory:'**Can** — умение/возможность.\nI can swim. She can cook.\n\n**Отрицание:** cannot / can\'t.\nI can\'t drive.\n\n**Вопрос:** Can you help? Yes, I can / No, I can\'t.',practice:'Расскажи 5 вещей, которые ты умеешь: I can...',memory:'Can = "могу". can — зелёная галочка, can\'t — красный крест.',keywords:'can ability'},
{id:'a1_17',level:'A1',title:'Like / Don\'t like + -ing',theory:'**Like** — нравится: I like coffee.\n**Love** — очень нравится: I love pizza.\n**Don\'t like** — не нравится.\n**Hate** — ненавижу.\n\n**После like/love/enjoy/hate + V-ing:**\nI like reading. I love cooking.',practice:'Расскажи про 5 вещей: I like..., I don\'t like...',memory:'Like + -ing (действие).',keywords:'likes dislikes gerund'},
{id:'a1_18',level:'A1',title:'Профессии и работа',theory:'teacher, doctor, engineer, lawyer, nurse, driver, cook, waiter, artist, programmer, manager, student, accountant, designer.\n\n**Вопрос:** What do you do?\n**Ответ:** I\'m a teacher. / I work as a manager.\n\n**Артикль a/an обязателен:** I\'m a doctor.',practice:'Назови 5 профессий друзей. What do they do?',memory:'Профессии группируй: медицина, IT, творчество.',keywords:'jobs professions'},
{id:'a1_19',level:'A1',title:'Хобби и свободное время',theory:'reading, sports, music, dancing, cooking, traveling, painting, gaming, photography, hiking, swimming, cycling.\n\n**Формулы:**\nI like reading.\nMy hobby is painting.\nI\'m good at singing.',practice:'Расскажи про 3 хобби: I like... My hobby is...',memory:'Хобби = то, что делаешь с удовольствием.',keywords:'hobbies free time'},
{id:'a1_20',level:'A1',title:'Погода и времена года',theory:'**Солнце:** It\'s sunny.\n**Дождь:** It\'s rainy.\n**Снег:** It\'s snowy.\n**Облачно:** It\'s cloudy.\n**Ветер:** It\'s windy.\n**Температура:** It\'s cold / warm / hot.\n\n**Вопрос:** What\'s the weather like?',practice:'Опиши сегодняшнюю погоду 5 предложениями.',memory:'Погода = it is + прилагательное.',keywords:'weather seasons'},
{id:'a1_21',level:'A1',title:'В магазине — диалоги',theory:'**Продавец:** Can I help you?\n**Клиент:** I\'d like..., How much is it?\n\n**Оплата:** cash / card. Here you go.\n\n**Диалог:**\n— Can I help you?\n— Yes, I\'d like this T-shirt.\n— What size?\n— Medium, please.',practice:'Разыграй диалог в магазине (7 реплик).',memory:'I\'d like = "я хотел бы" (вежливо).',keywords:'shopping dialogue'},
{id:'a1_22',level:'A1',title:'В кафе и ресторане',theory:'**Официант:** Are you ready to order?\n**Клиент:** I\'d like a coffee. / The bill, please.\n\n**Полезно:** tip, take away, table for two.',practice:'Составь заказ: I\'d like... + напиток + блюдо.',memory:'I\'d like = вежливый заказ.',keywords:'restaurant ordering'},
{id:'a1_23',level:'A1',title:'Транспорт и путешествия',theory:'**by bus / by train / by car / by plane / by bike / on foot.**\n\n**В аэропорту:** check-in, boarding pass, luggage, gate, departure, arrival.',practice:'Опиши, как ты добираешься на работу: I go by...',memory:'by = "на" (транспорте). on foot = пешком.',keywords:'transport travel'},
{id:'a1_24',level:'A1',title:'Дом и квартира',theory:'**Rooms:** living room, bedroom, kitchen, bathroom, hallway, balcony.\n**Furniture:** sofa, bed, table, chair, wardrobe, mirror, lamp.\n**Appliances:** fridge, washing machine, oven, microwave, TV.',practice:'Опиши свою квартиру: I have... My bedroom is...',memory:'Группируй по комнатам.',keywords:'home furniture'},
{id:'a1_25',level:'A1',title:'Итог A1 + тест памяти',theory:'**Ты знаешь:** алфавит, числа, семью, еду, базовые глаголы, Present Simple, to be, артикли.\n\n**Тест памяти:**\n1. Назови 12 месяцев\n2. 7 дней недели\n3. 10 цветов\n4. 5 профессий\n5. 10 продуктов',practice:'Рассказ о себе: имя, возраст, семья, работа, хобби, город, погода.',memory:'Повтори все темы A1 за 25 минут. Используй карточки Anki.',keywords:'review A1 test'},

/* ============ A2 — 25 УРОКОВ ============ */
{id:'a2_01',level:'A2',title:'Past Simple — правильные глаголы',theory:'**Формула:** V+ed. Work → worked. Play → played.\n\n**Правила:**\n• live → lived\n• stop → stopped (удвоение)\n• study → studied (y→ied)\n\n**Отрицание:** didn\'t + V1. I didn\'t work.\n**Вопрос:** Did you work? Yes, I did.',practice:'10 предложений о вчерашнем дне: Yesterday I worked...',memory:'-ed = "сделал в прошлом".',keywords:'past simple regular'},
{id:'a2_02',level:'A2',title:'Past Simple — неправильные глаголы',theory:'**Топ-30:** be→was/were, have→had, do→did, go→went, get→got, make→made, take→took, come→came, see→saw, know→knew, think→thought, say→said, find→found, give→gave, tell→told, become→became, leave→left, feel→felt, put→put, bring→brought, begin→began, keep→kept, hold→held, write→wrote, stand→stood, hear→heard.',practice:'Расскажи, что ты делал вчера (10 неправильных глаголов).',memory:'Группируй по паттернам: go-went, see-saw, take-took.',keywords:'irregular verbs'},
{id:'a2_03',level:'A2',title:'Past Continuous',theory:'**Формула:** was/were + V-ing.\nI was working. They were playing.\n\n**Когда:** длительное действие в прошлом.\n\n**Вместе с Past Simple:**\nI was reading when he came.',practice:'Опиши: что ты делал в 8 вечера вчера?',memory:'was/were + -ing = "был в процессе".',keywords:'past continuous'},
{id:'a2_04',level:'A2',title:'Future — will / going to',theory:'**Will** — решения, предсказания: I will help you.\n**Going to** — планы: I am going to travel.\n**Present Continuous** — договорённости: I am meeting John tomorrow.',practice:'5 планов: I\'m going to... 5 предсказаний: I think it will...',memory:'Will = спонтанно. Going to = план.',keywords:'future will going to'},
{id:'a2_05',level:'A2',title:'Степени сравнения',theory:'**Короткие:** +er / +est. big → bigger → the biggest.\n\n**Длинные:** more / most. interesting → more interesting.\n\n**Исключения:** good→better→best, bad→worse→worst, far→farther/further.',practice:'Сравни 5 пар: Moscow is bigger than...',memory:'-er/-est для коротких, more/most для длинных.',keywords:'comparatives superlatives'},
{id:'a2_06',level:'A2',title:'Some / Any / No',theory:'**Some** — утверждения: I have some money.\n**Any** — вопросы/отрицания: Do you have any money?\n**No** — нет совсем: I have no money.\n\n**Производные:** something, anything, nothing, somebody, anybody, nobody.',practice:'10 предложений с some/any/no + производные.',memory:'some = "есть", any = "?" или "нет", no = "ноль".',keywords:'some any no compounds'},
{id:'a2_07',level:'A2',title:'Much / Many / A lot of',theory:'**Many** — с исчисляемыми: many books.\n**Much** — с неисчисляемыми: much water.\n**A lot of** — универсально.\n\n**Few / A few:** few books (мало), a few books (немного).\n**Little / A little:** little water, a little water.',practice:'10 предложений: There is much..., There are many...',memory:'Many = много (считаем), Much = много (не считаем).',keywords:'quantifiers'},
{id:'a2_08',level:'A2',title:'Present Perfect',theory:'**Формула:** have/has + V3.\nI have worked. She has worked.\n\n**Когда:**\n• результат сейчас: I have lost my keys.\n• опыт: I have been to London.\n\n**Маркеры:** just, already, yet, ever, never, since, for.',practice:'10 предложений: Have you ever...? I have never...',memory:'have + V3 = "имею результат".',keywords:'present perfect'},
{id:'a2_09',level:'A2',title:'For / Since / Ago',theory:'**For** — длительность: for 5 years.\n**Since** — точка отсчёта: since 2020.\n**Ago** — назад от сейчас: 5 years ago.',practice:'5 предложений: I have... for... / since...',memory:'for = сколько, since = с какого момента, ago = тому назад.',keywords:'for since ago'},
{id:'a2_10',level:'A2',title:'Модальные — must / have to / should',theory:'**Must** — обязанность: You must wear a seatbelt.\n**Have to** — вынужден: I have to work.\n**Should** — совет: You should sleep more.\n**Mustn\'t** — запрет.\n**Don\'t have to** — не обязан.',practice:'5 советов другу: You should... 5 правил: You must...',memory:'Must = сам решил. Have to = заставили.',keywords:'modals obligation'},
{id:'a2_11',level:'A2',title:'Would like / Would love',theory:'**Would like** — вежливое "хочу": I would like a coffee.\n**Would love** — сильнее.\n**Would like to + V:** I would like to travel.\n\n**Отличие от want:** want — прямо, would like — вежливо.',practice:'Заказ в ресторане: I would like... 5 предложений с I\'d like to...',memory:'would like = "хотел бы" (вежливо).',keywords:'would like polite requests'},
{id:'a2_12',level:'A2',title:'Present Continuous vs Simple',theory:'**Simple** — привычки: I work every day.\n**Continuous** — сейчас: I am working now.\n\n**Глаголы-исключения (не в Continuous):** like, love, hate, want, need, know, understand, believe.',practice:'10 предложений: обычно vs сейчас.',memory:'Simple = всегда, Continuous = сейчас.',keywords:'simple vs continuous'},
{id:'a2_13',level:'A2',title:'Условные 1 типа (реальные)',theory:'**Реальное условие:**\nIf + Present Simple, will + V.\n\n**Пример:** If it rains, I will stay home.\n\n**Не will после if!** ❌ If it will rain...',practice:'5 предложений: If I have time, I will...',memory:'If = условие. Причина → следствие.',keywords:'conditionals 1'},
{id:'a2_14',level:'A2',title:'Условные 2 типа (нереальные)',theory:'**Нереальное:**\nIf + Past Simple, would + V.\n\n**Пример:** If I had money, I would travel. If I were you...\n\n**Were вместо was** для всех лиц.',practice:'5 мечт: If I had..., I would...',memory:'2 тип = мечта.',keywords:'conditionals 2'},
{id:'a2_15',level:'A2',title:'Прямая и косвенная речь',theory:'**Прямая:** He said, "I am tired."\n**Косвенная:** He said (that) he was tired.\n\n**Сдвиг времён:** Present → Past, will → would, can → could.',practice:'Переделай 5 предложений в косвенную речь.',memory:'Косвенная = сдвиг на шаг назад.',keywords:'reported speech'},
{id:'a2_16',level:'A2',title:'Пассивный залог',theory:'**Present:** am/is/are + V3. The book is written by Tolkien.\n\n**Past:** was/were + V3. The house was built last year.\n\n**Зачем:** фокус на действии, а не на том, кто делает.',practice:'Переделай 10 предложений в пассив.',memory:'be + V3 = "был сделан".',keywords:'passive voice'},
{id:'a2_17',level:'A2',title:'Вопросы — все типы',theory:'**Общий:** Do/Does/Did + S + V?\n**Специальный:** Wh- + вспом. + S + V?\nWhat do you do?\n\n**К подлежащему:** Who came? (без do!)\n**Альтернативный:** Do you like tea or coffee?',practice:'Задай 10 вопросов разных типов.',memory:'Вопрос = вспом. глагол вперёд.',keywords:'questions'},
{id:'a2_18',level:'A2',title:'Tag questions — хвостики',theory:'**Формула:** Утверждение + отрицательный хвост.\nYou are a student, aren\'t you?\nShe likes tea, doesn\'t she?\n\n**Отрицание + положительный хвост:**\nYou don\'t smoke, do you?\n\n**Особые:** Let\'s go, shall we? I am right, aren\'t I?',practice:'10 предложений с хвостами.',memory:'Хвост = противоположность.',keywords:'tag questions'},
{id:'a2_19',level:'A2',title:'Фразовые глаголы 1',theory:'get up, wake up, go on, come back, look for, look after, put on, take off, turn on/off, give up, find out, carry on, set up, put off, run out of.\n\n**Пример:** I get up at 7. Turn off the TV.',practice:'10 предложений с фразовыми глаголами.',memory:'Группируй по частице: up (завершение), off (отделение).',keywords:'phrasal verbs 1'},
{id:'a2_20',level:'A2',title:'Фразовые глаголы 2',theory:'get along, break down, give back, look forward to, take care of, come up with, put up with, get away with, make up, look up, turn out, work out, hang out, figure out, point out.',practice:'10 предложений с фразовыми глаголами 2.',memory:'look forward to = ждать с радостью.',keywords:'phrasal verbs 2'},
{id:'a2_21',level:'A2',title:'Идиомы 1',theory:'• Break a leg! — Удачи!\n• Piece of cake — проще простого\n• Hit the books — засесть за учёбу\n• Under the weather — неважно себя чувствую\n• Once in a blue moon — очень редко\n• Cost an arm and a leg — очень дорого',practice:'10 идиом — используй в диалоге.',memory:'Идиома = образ.',keywords:'idioms 1'},
{id:'a2_22',level:'A2',title:'Идиомы 2',theory:'• The ball is in your court — твой ход\n• Burn the midnight oil — работать допоздна\n• Blessing in disguise — не было бы счастья...\n• Get cold feet — струсить\n• It\'s raining cats and dogs — льёт как из ведра\n• Break the ice — растопить лёд',practice:'5 идиом в диалоге.',memory:'Визуализируй образ.',keywords:'idioms 2'},
{id:'a2_23',level:'A2',title:'Formal vs Informal',theory:'**Informal:** Hi! What\'s up? See ya!\n**Formal:** Dear Sir, I am writing to..., Yours sincerely.\n\n**Выбор зависит от:** письмо, email, разговор с начальником.',practice:'Напиши 2 версии одного письма.',memory:'Formal = галстук, Informal = футболка.',keywords:'formal informal register'},
{id:'a2_24',level:'A2',title:'Чтение и аудирование',theory:'**Стратегии чтения:**\n1. Skimming — быстро по заголовкам\n2. Scanning — поиск конкретного\n3. Detailed — глубокое чтение\n\n**Аудирование:** 6 Minute English, shadowing.',practice:'Прочти статью. Выдели 5 главных мыслей.',memory:'Skim = снять сливки (быстро). Scan = сканер (найти).',keywords:'reading listening strategies'},
{id:'a2_25',level:'A2',title:'Итог A2 + тест IQ',theory:'**Ты знаешь:** Past Simple, Continuous, Future, Present Perfect, модальные, условные 1-2, пассив, фразовые, идиомы.\n\n**IQ-тренировка:** рассказ о последнем отпуске (15-20 предложений), используя 5 времён.',practice:'Напиши рассказ о последнем отпуске.',memory:'Повтори все темы A2 за 30 минут.',keywords:'review A2 test IQ'},

/* ============ B1 — 25 УРОКОВ ============ */
{id:'b1_01',level:'B1',title:'Present Perfect Continuous',theory:'**Формула:** have/has been + V-ing.\n\nI have been working here for 5 years.\n\n**Отличие от Present Perfect:**\n• I have worked (завершено)\n• I have been working (продолжается)',practice:'10 предложений о том, что ты делаешь давно.',memory:'have been + -ing = "делаю и продолжаю".',keywords:'present perfect continuous'},
{id:'b1_02',level:'B1',title:'Past Perfect',theory:'**Формула:** had + V3.\n\nI had already eaten when he came.\n\n**Когда:** действие завершилось до другого прошлого действия.\n\nWhen I arrived, they had left.',practice:'5 историй с Past Perfect + Past Simple.',memory:'had + V3 = "уже было сделано до".',keywords:'past perfect'},
{id:'b1_03',level:'B1',title:'Past Perfect Continuous',theory:'**Формула:** had been + V-ing.\n\nShe had been working for 8 hours when she fell asleep.',practice:'5 предложений.',memory:'had been + -ing = "делал какое-то время до".',keywords:'past perfect continuous'},
{id:'b1_04',level:'B1',title:'Future Continuous',theory:'**Формула:** will be + V-ing.\n\nAt 8 PM, I will be watching TV.',practice:'5 предложений: At 8 PM tomorrow I will be...',memory:'will be + -ing = "буду делать в момент".',keywords:'future continuous'},
{id:'b1_05',level:'B1',title:'Future Perfect',theory:'**Формула:** will have + V3.\n\nBy 2030, I will have finished university.',practice:'5 предложений: By 2030, I will have...',memory:'will have + V3 = "уже сделаю к тому времени".',keywords:'future perfect'},
{id:'b1_06',level:'B1',title:'Модальные — вероятность',theory:'**Must** — 90% уверен: He must be at home.\n**Might / May** — 50%: He might be at home.\n**Can\'t** — 0%: He can\'t be at home.\n\n**Past:** must have + V3.',practice:'10 предположений о людях.',memory:'Must = уверен, Might = сомневаюсь, Can\'t = исключено.',keywords:'modals probability'},
{id:'b1_07',level:'B1',title:'Used to / Would / Be used to',theory:'**Used to** — привычка в прошлом (уже не так): I used to smoke.\n**Be used to** — привык: I am used to getting up early.\n**Get used to** — привыкаю.\n**Would** — повторяющееся действие.',practice:'5 предложений о детстве с used to.',memory:'used to = "раньше делал". be used to = "привык".',keywords:'used to would'},
{id:'b1_08',level:'B1',title:'Условные 3 типа (прошлое)',theory:'**Нереальное в прошлом:**\nIf + Past Perfect, would have + V3.\n\nIf I had studied harder, I would have passed.\n\n**Смешанные:**\nIf I had studied, I would be a doctor now.',practice:'5 сожалений: If I had..., I would have...',memory:'3 тип = сожаление о прошлом.',keywords:'conditionals 3'},
{id:'b1_09',level:'B1',title:'Wish / If only — желания',theory:'**Wish + Past Simple** — настоящее: I wish I knew.\n**Wish + Past Perfect** — прошлое: I wish I had known.\n**Wish + would** — раздражение: I wish you would stop.\n\n**If only** — сильнее.',practice:'10 желаний: I wish I... If only I...',memory:'wish = "хотел бы, но нет".',keywords:'wish if only'},
{id:'b1_10',level:'B1',title:'Косвенная речь — сложная',theory:'**Вопросы:**\nHe asked me where I lived.\nHe asked me if I was OK.\n\n**Команды:**\nHe told me to come.\nHe told me not to go.\n\n**Сдвиг:** now→then, today→that day, tomorrow→the next day.',practice:'10 предложений в косвенной речи.',memory:'Косвенная = пересказ.',keywords:'reported speech advanced'},
{id:'b1_11',level:'B1',title:'Relative clauses — придаточные',theory:'**Who** — люди: The man who called.\n**Which** — вещи: The book which I read.\n**That** — универсально.\n**Where** — места.\n**Whose** — принадлежность.',practice:'5 предложений с relative clauses.',memory:'who/which/that = "который".',keywords:'relative clauses'},
{id:'b1_12',level:'B1',title:'Gerund vs Infinitive',theory:'**Gerund (V-ing):** после предлогов, like, love, enjoy, hate, mind, finish, avoid, suggest.\n\n**Infinitive (to V):** после want, need, decide, hope, plan, learn, promise, agree.\n\n**Разница:** stop smoking (бросить) vs stop to smoke.',practice:'10 предложений: I enjoy... I want to...',memory:'Gerund = процесс, Infinitive = цель.',keywords:'gerund infinitive'},
{id:'b1_13',level:'B1',title:'Passive advanced — все времена',theory:'**Модальные в пассиве:** The work must be done.\n**Perfect:** The house has been built.\n**Continuous:** The house is being built.\n**Future:** The house will be built.',practice:'10 предложений в пассиве разных времён.',memory:'be + V3 = пассив.',keywords:'passive advanced'},
{id:'b1_14',level:'B1',title:'Tag questions advanced',theory:'**Интонация:** ↘ уверен, ↗ спрашиваю.\n\n**Особые:**\nLet\'s go, shall we?\nI am right, aren\'t I?\nNobody came, did they?',practice:'10 вопросов с хвостами.',memory:'Хвост = противоположность.',keywords:'tag questions advanced'},
{id:'b1_15',level:'B1',title:'Emphasis — do/does/did',theory:'**Усиление:**\nI do love you.\nHe does work hard.\nI did call you!\n\n**Инверсия после never:**\nNever have I seen such a thing.',practice:'5 эмфатических предложений. 5 с инверсией.',memory:'do/does/did = "действительно".',keywords:'emphasis inversion'},
{id:'b1_16',level:'B1',title:'Деловой английский — email',theory:'**Структура:**\n1. Subject (тема)\n2. Salutation: Dear Mr. Smith,\n3. Opening: I am writing to...\n4. Body\n5. Closing: Best regards,\n6. Signature\n\n**Фразы:** Please find attached..., Looking forward to hearing from you.',practice:'Напиши деловой email на 100 слов.',memory:'Email = структура.',keywords:'business email'},
{id:'b1_17',level:'B1',title:'Деловой английский — звонок',theory:'**Начало:** Good morning, this is...\n**Соединение:** Could I speak to...?\n**Уточнение:** Could you repeat, please?\n**Завершение:** Thank you for your time.',practice:'Разыграй деловой звонок (10 реплик).',memory:'Звонок = приветствие + цель + уточнения.',keywords:'business call'},
{id:'b1_18',level:'B1',title:'Презентации — структура',theory:'**Структура:**\n1. Greeting\n2. Topic: Today I will talk about...\n3. Outline: First..., then..., finally...\n4. Body\n5. Conclusion: To sum up...\n6. Q&A',practice:'Подготовь 3-минутную презентацию.',memory:'Презентация = крючок + структура + вывод.',keywords:'presentations'},
{id:'b1_19',level:'B1',title:'Интервью на работу',theory:'**Топ-вопросы:**\n• Tell me about yourself.\n• Why do you want this job?\n• What are your strengths?\n• What are your weaknesses?\n• Where do you see yourself in 5 years?\n\n**STAR:** Situation, Task, Action, Result.',practice:'Ответь на 5 вопросов интервью.',memory:'STAR = 4 шага.',keywords:'interview'},
{id:'b1_20',level:'B1',title:'Идиомы деловые',theory:'• Touch base — связаться\n• Circle back — вернуться\n• Think outside the box — нестандартно\n• Get the ball rolling — начать\n• On the same page — согласны\n• Low-hanging fruit — лёгкая цель\n• Win-win — обоюдная выгода',practice:'5 идиом в деловом контексте.',memory:'Визуализируй офис.',keywords:'business idioms'},
{id:'b1_21',level:'B1',title:'Сокращения и сленг',theory:'**В чатах:**\n• ASAP — как можно скорее\n• FYI — к сведению\n• BTW — кстати\n• IMO — по-моему\n• BRB — скоро вернусь\n• LOL, OMG, TBH, IDK\n\n**Сленг:** chill, cool, awesome, hang out.',practice:'10 сообщений с сокращениями.',memory:'Сокращения = первые буквы.',keywords:'abbreviations slang'},
{id:'b1_22',level:'B1',title:'Collocations — устойчивые сочетания',theory:'**Make vs Do:**\n• Make: a decision, a mistake, money, coffee.\n• Do: homework, sports, the dishes.\n\n**Take/Have/Get:**\n• Take: a break, a shower, a photo\n• Have: breakfast, fun, time\n• Get: ready, married, a job',practice:'20 коллокаций — используй в предложениях.',memory:'Make = создавать, Do = выполнять.',keywords:'collocations'},
{id:'b1_23',level:'B1',title:'Word formation — словообразование',theory:'**Suffixes:**\n• -tion: information\n• -ment: development\n• -ness: happiness\n• -ity: productivity\n• -er/-or: teacher, actor\n\n**Prefixes:**\n• un-: unhappy\n• dis-: disagree\n• re-: redo\n• pre-: preview',practice:'Образуй 30 слов от корней.',memory:'Prefix = значение, Suffix = часть речи.',keywords:'word formation'},
{id:'b1_24',level:'B1',title:'Чтение и анализ текста',theory:'**Стратегии:**\n1. Skimming\n2. Scanning\n3. Detailed\n\n**Работа с незнакомыми словами:** контекст, корень, догадка.\n\n**Заметки:** Cornell method, mind maps.',practice:'Прочти статью B1. Выдели 5 главных мыслей.',memory:'Skim = снять сливки (быстро).',keywords:'reading analysis'},
{id:'b1_25',level:'B1',title:'Итог B1 + тест IQ',theory:'Уровень B1 — уверенное общение на бытовые и профессиональные темы.\n\n**Тест памяти:** 5 времён, 20 фразовых, 10 идиом, 10 коллокаций.',practice:'Напиши эссе 200 слов на любую тему.',memory:'Повтори все темы B1 за 40 минут.',keywords:'review B1 test IQ'},

/* ============ B2 — 25 УРОКОВ ============ */
{id:'b2_01',level:'B2',title:'Инверсия — продвинутая',theory:'**После отрицательных наречий:**\nNever have I seen...\nRarely does he...\nNot only did she..., but she also...\n\n**После Only:**\nOnly then did I understand.\n\n**После No sooner:**\nNo sooner had I arrived than...',practice:'10 инверсий.',memory:'Инверсия = вспом. глагол перед подлежащим.',keywords:'inversion'},
{id:'b2_02',level:'B2',title:'Смешанные условные',theory:'**Прошлое + настоящее:**\nIf I had studied medicine, I would be a doctor now.\n\n**Настоящее + прошлое:**\nIf I were rich, I would have bought that house.',practice:'5 смешанных условных.',memory:'Смешанные = прошлое влияет на настоящее.',keywords:'mixed conditionals'},
{id:'b2_03',level:'B2',title:'Cleft sentences — расщеплённые',theory:'**It-cleft:** It was John who broke the window.\n\n**What-cleft:** What I need is a holiday.\n\n**The reason why I left was...**',practice:'10 cleft-предложений.',memory:'Cleft = разделяю на две части.',keywords:'cleft sentences'},
{id:'b2_04',level:'B2',title:'Subjunctive — сослагательное',theory:'**Формальная речь:**\nI suggest that he be present.\nIt is essential that she arrive on time.\n\n**После:** suggest, recommend, demand, insist, require, essential, vital, important.',practice:'10 предложений.',memory:'Subjunctive = форма without -s.',keywords:'subjunctive'},
{id:'b2_05',level:'B2',title:'Фразовые глаголы продвинутые',theory:'• put up with — терпеть\n• come up with — придумать\n• look down on — смотреть свысока\n• get away with — избежать наказания\n• do away with — отменить\n• make up for — компенсировать\n• look forward to — ждать\n• take up — заняться\n• turn down — отклонить\n• bring about — вызвать',practice:'10 предложений.',memory:'Группируй по частице.',keywords:'phrasal advanced'},
{id:'b2_06',level:'B2',title:'Идиомы B2',theory:'• Bite the bullet — решиться\n• Beat around the bush — ходить вокруг да около\n• Cut corners — срезать углы\n• Hit the nail on the head — попасть в точку\n• Pull someone\'s leg — разыгрывать\n• Sit on the fence — занимать нейтралитет\n• Throw in the towel — сдаться\n• Go back to the drawing board — начать заново',practice:'10 идиом B2.',memory:'Визуализируй образ каждой идиомы.',keywords:'idioms B2'},
{id:'b2_07',level:'B2',title:'Discourse markers — связки',theory:'**Добавление:** moreover, furthermore, in addition.\n**Контраст:** however, nevertheless, on the other hand.\n**Причина:** because of, due to, owing to.\n**Следствие:** therefore, consequently, as a result.\n**Пример:** for instance, such as.',practice:'Эссе с 10 маркерами.',memory:'Связки = дорожные знаки в тексте.',keywords:'discourse markers'},
{id:'b2_08',level:'B2',title:'Формальная vs академическая речь',theory:'**Неформально:** get, a lot of, kids, stuff.\n**Формально:** obtain, numerous, children, material.\n\n**Хеджирование:** It could be argued, It seems likely, There is evidence to suggest...',practice:'Переведи 10 предложений в академический стиль.',memory:'Академический = отстранённость + точность.',keywords:'academic style'},
{id:'b2_09',level:'B2',title:'Аргументация',theory:'**Структура:**\n1. Claim — утверждение\n2. Evidence — доказательство\n3. Warrant — обоснование\n4. Rebuttal — опровержение\n5. Conclusion — вывод\n\n**Фразы:** It is widely believed that..., Conversely, critics argue...',practice:'Подготовь аргумент "за" и "против" по теме.',memory:'Аргумент = тезис + доказательство.',keywords:'argumentation'},
{id:'b2_10',level:'B2',title:'Публичные выступления',theory:'**Hook:** вопрос, история, статистика.\n**Структура:** 3 главных пункта.\n**Power phrases:** Imagine..., The truth is..., Here\'s the thing...\n**Паузы:** работают сильнее слов.',practice:'Подготовь 5-минутную речь.',memory:'Речь = крючок + 3 пункта + вывод.',keywords:'public speaking'},
{id:'b2_11',level:'B2',title:'Переговоры',theory:'**BATNA** — лучшая альтернатива.\n**Фразы:**\n• What if we...\n• Let\'s find a middle ground.\n• That works for me.\n• I\'m afraid that\'s not possible.\n\n**Тактики:** anchoring, framing, silence.',practice:'Разыграй переговоры.',memory:'BATNA = твой план Б.',keywords:'negotiation'},
{id:'b2_12',level:'B2',title:'Дебаты',theory:'**Структура:**\n1. Opening statement\n2. Arguments\n3. Rebuttal\n4. Closing\n\n**Фразы:** I strongly believe..., On the contrary, My opponent claims...',practice:'Дебаты на 5 минут.',memory:'Дебаты = тезис + аргументы + опровержение.',keywords:'debate'},
{id:'b2_13',level:'B2',title:'Идиомы в контексте',theory:'• Once in a blue moon\n• Bury the hatchet — помириться\n• See eye to eye — соглашаться\n• A blessing in disguise\n• The last straw\n• Jump on the bandwagon — следовать моде',practice:'Составь диалог с 5 идиомами.',memory:'Визуализируй каждую идиому.',keywords:'idioms context'},
{id:'b2_14',level:'B2',title:'Интервью на работу B2',theory:'**Поведенческие вопросы:**\n• Tell me about a time when...\n• How do you handle...\n• What\'s your biggest achievement?\n\n**STAR:** Situation, Task, Action, Result.',practice:'Ответь на 5 STAR-вопросов.',memory:'STAR = 4 шага.',keywords:'behavioral interview'},
{id:'b2_15',level:'B2',title:'Рецензия / обзор',theory:'**Структура:**\n1. Introduction\n2. Summary\n3. Analysis\n4. Evaluation\n5. Recommendation\n\n**Фразы:** The film is..., I would recommend...',practice:'Напиши рецензию на фильм 200 слов.',memory:'Рецензия = описание + анализ + оценка.',keywords:'review'},
{id:'b2_16',level:'B2',title:'Научная статья — структура',theory:'**Структура:** Abstract, Intro, Methods, Results, Discussion, Conclusion.\n\n**Фразы:** This paper examines..., The findings suggest..., Further research is needed.',practice:'Напиши abstract на 100 слов.',memory:'IMRaD = Intro, Methods, Results, Discussion.',keywords:'scientific article'},
{id:'b2_17',level:'B2',title:'Разговорный B2',theory:'**Вводные:** Well, you know, I mean, actually, basically.\n**Эмоции:** I\'m thrilled, I\'m fed up, It drives me crazy.\n**Мягкое несогласие:** I see your point, but...',practice:'Диалог с 10 разговорными фразами.',memory:'Разговорный = естественность.',keywords:'conversational'},
{id:'b2_18',level:'B2',title:'Нюансы тона',theory:'**Вежливо:** Could you possibly...?\n**Нейтрально:** Can you...?\n**Прямо:** Do it.\n\n**Сарказм, шутка, серьёзность** — через контекст и интонацию.',practice:'Одна просьба — 5 тонов.',memory:'Тон = отношение.',keywords:'tone register'},
{id:'b2_19',level:'B2',title:'Collocations B2',theory:'• Take measures\n• Draw a conclusion\n• Meet a deadline\n• Raise awareness\n• Reach an agreement\n• Bridge the gap\n• Make a difference\n• Pay attention',practice:'20 коллокаций B2.',memory:'Коллокации = устойчивые пары.',keywords:'collocations B2'},
{id:'b2_20',level:'B2',title:'Narrative tenses',theory:'**Комбо:**\nPast Simple, Past Continuous, Past Perfect, Past Perfect Continuous.\n\nI was walking home when I saw him. He had been waiting for an hour.',practice:'Напиши историю 200 слов, используя 4 времени.',memory:'Рассказ = фон + событие + предыстория.',keywords:'narrative tenses'},
{id:'b2_21',level:'B2',title:'Ellipsis & Substitution',theory:'**Ellipsis:**\n— Would you like tea?\n— I\'d love to.\n\n**Substitution:**\nThe blue one. The one I told you about.',practice:'10 предложений с эллипсисом.',memory:'Эллипсис = пропуск очевидного.',keywords:'ellipsis substitution'},
{id:'b2_22',level:'B2',title:'Idiomatic expressions B2',theory:'• Break the ice\n• Bend over backwards — очень стараться\n• Go the extra mile\n• Bite off more than you can chew\n• Have a lot on your plate\n• In the same boat',practice:'5 диалогов с идиомами.',memory:'Визуализируй образ.',keywords:'idiomatic B2'},
{id:'b2_23',level:'B2',title:'Advanced phrasal verbs',theory:'• Account for — объяснять\n• Bring about — вызывать\n• Carry out — выполнять\n• Come down to — сводиться к\n• End up — оказаться\n• Figure out — понять\n• Point out — указать\n• Sort out — разобраться',practice:'10 предложений.',memory:'Группируй по значению.',keywords:'advanced phrasal'},
{id:'b2_24',level:'B2',title:'Формальные письма',theory:'**Complaint:**\nDear Sir/Madam, I am writing to complain about...\n\n**Application:**\nI am writing to apply for...\n\n**Request:**\nI would be grateful if you could...',practice:'Напиши 3 формальных письма.',memory:'Формальное письмо = структура + вежливость.',keywords:'formal letters'},
{id:'b2_25',level:'B2',title:'Итог B2 + тест IQ',theory:'Уровень B2 — сложные тексты, абстрактные темы, свободное общение с носителями.\n\n**Тест памяти:** 5 условных, 10 фразовых, 10 идиом, 10 коллокаций.',practice:'Эссе 300 слов с аргументацией.',memory:'Повтори все темы B2 за 50 минут.',keywords:'review B2 test IQ'},

/* ============ C1 — 25 УРОКОВ ============ */
{id:'c1_01',level:'C1',title:'Nuances of meaning — оттенки',theory:'**Синонимы с оттенками:**\n• house / home / dwelling / residence\n• smart / intelligent / clever / bright\n• thin (нейтр.) / skinny (отриц.) / slim (поз.)\n\n**Коннотации:**\n• cheap (нейтр.) / inexpensive (эвфемизм) / affordable (доступный)',practice:'Найди оттенки 10 пар слов.',memory:'Коннотация = эмоциональная окраска.',keywords:'nuance connotation'},
{id:'c1_02',level:'C1',title:'Idioms C1',theory:'• It takes two to tango\n• To be on the fence\n• Don\'t count your chickens\n• Throw someone under the bus\n• Play devil\'s advocate\n• Take it with a grain of salt\n• Have an axe to grind\n• Burn bridges',practice:'10 идиом C1 в контексте.',memory:'Визуализируй образ.',keywords:'idioms C1'},
{id:'c1_03',level:'C1',title:'Academic writing — hedging',theory:'**Hedging:**\n• It could be argued that...\n• There is evidence to suggest...\n• It appears to be...\n• This may be due to...\n\n**Avoid:** I think, very, really, a lot.',practice:'Напиши абзац с hedging.',memory:'Hedging = осторожность.',keywords:'academic writing hedging'},
{id:'c1_04',level:'C1',title:'Literary devices — приёмы',theory:'• Metaphor: Time is a thief.\n• Simile: Fast as lightning.\n• Personification: The wind whispered.\n• Alliteration: Silent sea.\n• Hyperbole: A million times.\n• Oxymoron: Deafening silence.',practice:'Напиши 5 предложений с приёмами.',memory:'Приёмы = украшения текста.',keywords:'literary devices'},
{id:'c1_05',level:'C1',title:'Register — регистры речи',theory:'**Frozen:** legal documents.\n**Formal:** academic, business.\n**Consultative:** teacher-student.\n**Casual:** friends.\n**Intimate:** family, partner.\n\n**Mixing регистров = ошибка.**',practice:'Одна тема — 5 регистров.',memory:'Регистр = одежда для речи.',keywords:'register'},
{id:'c1_06',level:'C1',title:'Сочинение-рассуждение',theory:'**Структура:**\n1. Intro + тезис\n2. Аргумент 1 + пример\n3. Аргумент 2 + пример\n4. Контраргумент + опровержение\n5. Заключение\n\n**Объём:** 400-500 слов.',practice:'Сочинение 400 слов.',memory:'Сочинение = тезис + аргументы + вывод.',keywords:'essay'},
{id:'c1_07',level:'C1',title:'Стилистические приёмы',theory:'• Anaphora: I have a dream...\n• Chiasmus: Ask not what your country can do for you...\n• Antithesis: It was the best of times, it was the worst of times.\n• Rhetorical question: Is this fair?',practice:'5 предложений с приёмами.',memory:'Визуализируй речь.',keywords:'stylistic devices'},
{id:'c1_08',level:'C1',title:'Дебаты C1',theory:'**Структура:**\n1. Position\n2. Evidence\n3. Rebuttal\n4. Cross-examination\n5. Closing\n\n**Фразы:** I take issue with..., My learned friend..., I beg to differ.',practice:'Дебаты на 10 минут.',memory:'Дебаты = позиция + доказательства + опровержение.',keywords:'debate C1'},
{id:'c1_09',level:'C1',title:'Публичная речь',theory:'**Hook + Story + Point + Call to action.**\n**Приёмы:** rule of three, repetition, pause, volume.\n**Цитаты:** Churchill, MLK, Jobs.',practice:'Речь 5 минут с 3 приёмами.',memory:'Речь = история + эмоция + действие.',keywords:'public speech'},
{id:'c1_10',level:'C1',title:'Юмор на английском',theory:'**Types:** puns, irony, sarcasm, deadpan, self-deprecating.\n**Тонкая грань:** некоторые шутки могут оскорбить.\n**Безопасно:** self-deprecating, observational.',practice:'5 шуток разных типов.',memory:'Юмор = неожиданность.',keywords:'humor'},
{id:'c1_11',level:'C1',title:'Cleft & Inversion advanced',theory:'**Emphatic do:** I do apologize.\n**Fronting:** Off went the alarm.\n**Negative inversion:** Under no circumstances will I agree.',practice:'10 предложений.',memory:'Инверсия = переворот.',keywords:'cleft inversion'},
{id:'c1_12',level:'C1',title:'Cohesion — связность',theory:'**Cohesive devices:**\n• Reference: this, that, it\n• Substitution\n• Ellipsis\n• Conjunction\n• Lexical cohesion: synonyms, antonyms\n\n**Цель:** текст читается как единое целое.',practice:'Возьми текст и выдели все связки.',memory:'Cohesion = клей текста.',keywords:'cohesion'},
{id:'c1_13',level:'C1',title:'Coherence — логичность',theory:'**Порядок абзацев:**\n1. Topic sentence\n2. Supporting\n3. Example\n4. Concluding\n\n**Тематическая прогрессия:** каждая новая фраза продолжает предыдущую.',practice:'Перепиши текст с coherence.',memory:'Coherence = логика.',keywords:'coherence'},
{id:'c1_14',level:'C1',title:'Критическое мышление',theory:'**Фреймворк:**\n1. What is the claim?\n2. What is the evidence?\n3. Is the reasoning valid?\n4. What are the counterarguments?\n5. What is my conclusion?',practice:'Проанализируй статью по фреймворку.',memory:'Критическое мышление = вопросы.',keywords:'critical thinking'},
{id:'c1_15',level:'C1',title:'Сложные тексты',theory:'**Работа:**\n1. Skim — общее\n2. Scan — конкретное\n3. Close reading — глубоко\n\n**Заметки:** Cornell method, mind maps.',practice:'Прочти статью, составь mind map.',memory:'Визуализируй структуру.',keywords:'complex texts'},
{id:'c1_16',level:'C1',title:'Литературный анализ',theory:'**Элементы:**\n• Theme\n• Character\n• Plot\n• Setting\n• Point of view\n• Symbolism',practice:'Анализ короткого рассказа.',memory:'Анализ = элементы + связи.',keywords:'literary analysis'},
{id:'c1_17',level:'C1',title:'Научный стиль',theory:'**Особенности:**\n• Passive voice\n• Nominalization\n• Precise vocabulary\n• Citations\n\n**Фразы:** It has been demonstrated that..., The data suggests...',practice:'Напиши научный abstract.',memory:'Научный стиль = отстранённость.',keywords:'scientific style'},
{id:'c1_18',level:'C1',title:'Юридический английский',theory:'**Термины:** plaintiff, defendant, contract, tort, damages.\n**Фразы:** hereby, thereto, notwithstanding.',practice:'Разбери контракт, выпиши 10 терминов.',memory:'Юридический = точность.',keywords:'legal English'},
{id:'c1_19',level:'C1',title:'Медицинский английский',theory:'**Термины:** diagnosis, symptoms, treatment, prescription.\n**Фразы:** The patient presents with..., A thorough examination revealed...',practice:'Напиши мед. отчёт 200 слов.',memory:'Медицинский = точность.',keywords:'medical English'},
{id:'c1_20',level:'C1',title:'IT-английский',theory:'**Термины:** API, deployment, scalability, latency.\n**Фразы:** We need to optimize..., The system is down, Let\'s roll back.',practice:'Напиши техническое описание 200 слов.',memory:'IT = точность + краткость.',keywords:'IT English'},
{id:'c1_21',level:'C1',title:'Бизнес-презентация',theory:'**Структура:**\n1. Hook\n2. Problem\n3. Solution\n4. Market\n5. Team\n6. Traction\n7. Ask\n\n**Pitch:** 3-5 минут.',practice:'Питч стартапа.',memory:'Питч = проблема + решение + рынок + команда.',keywords:'business pitch'},
{id:'c1_22',level:'C1',title:'Переговоры C1',theory:'**Тактики:**\n• Anchoring\n• Framing\n• BATNA\n• MESO (Multiple Equivalent Simultaneous Offers)\n• Silence',practice:'Разыграй сложные переговоры.',memory:'Переговоры = подготовка + тактика.',keywords:'negotiation C1'},
{id:'c1_23',level:'C1',title:'Медиация',theory:'**Структура:**\n1. Intro\n2. Issues\n3. Interests\n4. Options\n5. Agreement\n\n**Фразы:** Let\'s find common ground..., I hear you saying...',practice:'Проведи медиацию конфликта.',memory:'Медиация = слушание + поиск решения.',keywords:'mediation'},
{id:'c1_24',level:'C1',title:'Философия языка',theory:'**Идеи:**\n• Sapir-Whorf (язык = мышление)\n• Wittgenstein (языковые игры)\n• Chomsky (универсальная грамматика)\n• Austin (речевые акты)',practice:'Эссе на 400 слов.',memory:'Философия = вопросы.',keywords:'philosophy of language'},
{id:'c1_25',level:'C1',title:'Итог C1 + тест IQ',theory:'Уровень C1 — свободное владение, сложные тексты, тонкие нюансы.\n\n**Тест памяти:** 10 идиом, 10 коллокаций, 5 стилистических приёмов, 3 регистра.',practice:'Эссе 500 слов с академическим стилем.',memory:'Повтори все темы C1 за 60 минут.',keywords:'review C1 test IQ'}
];

/* ============ MEMORY_MODULE ============ */
var MEMORY_MODULE=[
{id:'mem_01',level:'Memory',title:'Как работает память',theory:'**3 типа памяти:**\n• Сенсорная (0.5-3 сек)\n• Краткосрочная (15-30 сек, 7±2 элемента)\n• Долгосрочная (неограниченно)\n\n**Кривая забывания Эббингауза:**\n• 20 мин → 58% забыто\n• 1 час → 64%\n• 1 день → 67%\n• 1 неделя → 75%\n\n**Вывод:** повторяй через 1ч, 1д, 3д, 7д, 30д.',practice:'Составь расписание повторений на неделю для 10 новых слов.',memory:'Кривая Эббингауза = обрыв вниз. Визуализируй график.',keywords:'memory Ebbinghaus'},
{id:'mem_02',level:'Memory',title:'Метод локусов (Дворец памяти)',theory:'**Древнегреческий метод:**\n1. Выбери знакомое место (квартира)\n2. Определи 10 точек (дверь, зеркало, шкаф...)\n3. Размести образы в точках\n4. Пройди маршрут мысленно\n\n**Пример:** 10 слов → 10 точек в квартире.',practice:'Размести 10 английских слов в своей квартире. Пройди маршрут 3 раза.',memory:'Локусы = места. Чем ярче образ, тем лучше запомнишь.',keywords:'method of loci memory palace'},
{id:'mem_03',level:'Memory',title:'Мнемоника — ассоциации',theory:'**Типы мнемоник:**\n• Акроним: NASA, FAQ\n• Акростих: Every Good Boy Does Fine (ноты)\n• Рифма: "I before E except after C"\n• История: свяжи слова в сюжет\n• Числа-образы: 1=свеча, 2=лебедь\n\n**Пример:** To remember "necessary" — 1 Collar, 2 Sleeves (1 C, 2 S).',practice:'Придумай мнемонику для 10 сложных английских слов.',memory:'Мнемоника = крючок. Чем страннее, тем лучше.',keywords:'mnemonics'},
{id:'mem_04',level:'Memory',title:'Интервальное повторение (Anki)',theory:'**Принцип:** повторяй в момент, когда почти забыл.\n\n**Интервалы:**\n1 день → 3 дня → 7 дней → 14 → 30 → 60 → 120\n\n**Anki:** карточка, оценка 1-4, алгоритм сам подбирает интервал.\n\n**Правило:** 20 минут в день лучше 3 часов раз в неделю.',practice:'Создай 20 карточек Anki по текущему уроку. Повтори 3 дня.',memory:'Anki = умное повторение. Визуализируй календарь.',keywords:'spaced repetition Anki'},
{id:'mem_05',level:'Memory',title:'Чанкинг — группировка',theory:'**Chunking:** краткосрочная память держит 7±2 элемента. Группируй → больше.\n\n**Пример:**\n• 9 1 7 5 5 5 1 2 3 4 → 917-555-1234 (3 чанка)\n• Слова: apple, banana, orange → фрукты\n\n**В английском:** фразы, коллокации, идиомы — чанки.',practice:'Сгруппируй 30 английских слов в 6 чанков по 5. Запомни.',memory:'Chunk = кусок. Мозг любит паттерны.',keywords:'chunking'},
{id:'mem_06',level:'Memory',title:'Активное припоминание',theory:'**Testing effect:** попытка вспомнить укрепляет память сильнее, чем перечитывание.\n\n**Методы:**\n• Flash-карточки\n• Тесты без подсказок\n• Объясни вслух\n• Напиши по памяти\n\n**Правило:** 70% времени — припоминание, 30% — чтение.',practice:'Закрой урок. Напиши всё, что помнишь. Проверь. Повтори пробелы.',memory:'Recall > Recognition. Мозг учится, когда напрягается.',keywords:'active recall testing effect'},
{id:'mem_07',level:'Memory',title:'Метод Фейнмана',theory:'**4 шага:**\n1. Выбери концепт\n2. Объясни 12-летнему\n3. Найди пробелы\n4. Упрости и повтори\n\n**Пример:** объясни Present Perfect ребёнку.',practice:'Объясни 3 темы из обучения простыми словами. Запиши.',memory:'Если не можешь объяснить — не понял.',keywords:'Feynman technique'},
{id:'mem_08',level:'Memory',title:'Сон и память',theory:'**Консолидация памяти во сне:**\n• Медленный сон: факты\n• REM-сон: эмоции, навыки\n• 7-9 часов критично\n\n**Правило:** учи перед сном, повторяй утром.',practice:'Учи 10 слов перед сном. Утром проверь без подсказок.',memory:'Сон = сохранение. Без сна память не работает.',keywords:'sleep memory consolidation'},
{id:'mem_09',level:'Memory',title:'Двойное кодирование',theory:'**Paivio:** мозг запоминает лучше, если задействованы и слова, и образы.\n\n**Метод:**\n• Слово + картинка\n• Текст + схема\n• Лекция + mind map\n\n**Пример:** "apple" + образ красного яблока + запах.',practice:'Нарисуй mind map по 3 урокам. Добавь символы.',memory:'Слово + образ = двойной след в памяти.',keywords:'dual coding'},
{id:'mem_10',level:'Memory',title:'Итог: система памяти',theory:'**Твоя система:**\n1. Учи активно (recall)\n2. Повторяй интервально (Anki)\n3. Используй локусы для списков\n4. Мнемоники для сложного\n5. Чанкинг для объёма\n6. Спи 7-9 часов\n7. Учи перед сном\n\n**Результат:** память × 3-5 за месяц.',practice:'Составь личную систему на месяц. Отслеживай.',memory:'Система > мотивация.',keywords:'memory system'}
];

/* ============ IQ_MODULE ============ */
var IQ_MODULE=[
{id:'iq_01',level:'IQ',title:'Что такое IQ',theory:'**IQ = интеллект-коэффициент.** Средний = 100, σ = 15.\n\n**Компоненты:**\n• Логика\n• Пространственное мышление\n• Вербальное\n• Рабочая память\n• Скорость обработки\n\n**Тест Равена, Векслера, Айзенка.**',practice:'Пройди бесплатный тест IQ Равена онлайн. Запиши результат.',memory:'IQ = не фикс. Тренируется.',keywords:'IQ intelligence'},
{id:'iq_02',level:'IQ',title:'Логические последовательности',theory:'**Типы:**\n• Арифметические: 2, 4, 6, 8...\n• Геометрические: 2, 4, 8, 16...\n• Фибоначчи: 1, 1, 2, 3, 5, 8...\n• Смешанные: +2, ×2, +3, ×3...\n\n**Стратегия:** ищи разницу, отношение, чередование.',practice:'Реши 10 последовательностей:\n1. 1, 4, 9, 16, ?\n2. 2, 6, 12, 20, ?\n3. 1, 1, 2, 3, 5, ?\n4. 3, 6, 12, 24, ?\n5. 100, 50, 25, ?',memory:'Ищи паттерн: +, ×, чередование.',keywords:'logic sequences'},
{id:'iq_03',level:'IQ',title:'Аналогии',theory:'**Формула:** A : B = C : ?\n\n**Типы связей:**\n• Часть-целое: колесо : машина\n• Противоположность: горячий : холодный\n• Функция: нож : резать\n• Категория: яблоко : фрукт\n\n**Пример:** doctor : hospital = teacher : ? (school)',practice:'Реши 10 аналогий:\n1. книга : читать = нож : ?\n2. кот : мяукать = собака : ?\n3. рука : перчатка = нога : ?\n4. вода : лёд = пар : ?\n5. врач : больница = повар : ?',memory:'Аналогия = связь. Найди отношение.',keywords:'analogies'},
{id:'iq_04',level:'IQ',title:'Пространственное мышление',theory:'**Тренировка:**\n• Мысленное вращение фигур\n• Развёртки куба\n• Танграм\n• Тетрис\n• Шахматы\n\n**Пример:** кубик Рубика — 43 квинтиллиона комбинаций.',practice:'Собери развёртку куба мысленно. Реши 5 задач на вращение.',memory:'Пространственное = правое полушарие. Визуализируй.',keywords:'spatial thinking'},
{id:'iq_05',level:'IQ',title:'Рабочая память',theory:'**Рабочая память = 4±1 чанка.** Тренируется.\n\n**Упражнения:**\n• N-back (запомни N шагов назад)\n• Двойная задача\n• Запоминание чисел\n• Обратный счёт\n\n**Пример:** 7 3 9 1 5 → запомни → произнеси в обратном порядке.',practice:'Играй в N-back 10 минут в день. Запоминай 7-значные числа.',memory:'Рабочая память = RAM. Тренируй.',keywords:'working memory'},
{id:'iq_06',level:'IQ',title:'Скорочтение',theory:'**Средняя скорость:** 200-250 слов/мин.\n**Цель:** 400-600 слов/мин.\n\n**Техники:**\n• Убрать субвокализацию\n• Читать блоками (3-5 слов)\n• Указка/палец\n• Не возвращаться назад',practice:'Читай 10 минут с указкой. Замерь скорость. Повтори через неделю.',memory:'Глаза двигаются скачками. Убирай регрессии.',keywords:'speed reading'},
{id:'iq_07',level:'IQ',title:'Критическое мышление',theory:'**5 вопросов:**\n1. Кто говорит?\n2. Что утверждает?\n3. Какие доказательства?\n4. Какие альтернативы?\n5. Что если ошибается?\n\n**Ловушки:**\n• Confirmation bias\n• Ad hominem\n• Straw man\n• False dichotomy',practice:'Проанализируй новость по 5 вопросам. Найди 3 ловушки.',memory:'Критическое = вопросы. Не верь сразу.',keywords:'critical thinking'},
{id:'iq_08',level:'IQ',title:'Математическое мышление',theory:'**Тренировка:**\n• Ментальная арифметика\n• Оценка (estimation)\n• Проценты в уме\n• Вероятность\n\n**Пример:** 15% от 200 = 30. 17×23 = 391.\n**Лайфхак:** 17×23 = (20-3)(20+3) = 400-9 = 391.',practice:'Реши в уме 20 примеров. Оцени 10 покупок.',memory:'Математика = паттерны. Ищи упрощения.',keywords:'math mental arithmetic'},
{id:'iq_09',level:'IQ',title:'Шахматы и стратегия',theory:'**Шахматы развивают:**\n• Планирование\n• Рабочую память\n• Пространственное мышление\n• Терпение\n\n**Основы:**\n• Контроль центра\n• Развитие фигур\n• Безопасность короля\n• Тактика: вилка, связка, мат',practice:'Играй 1 партию в день. Реши 5 тактических задач.',memory:'Шахматы = IQ-спорт.',keywords:'chess strategy'},
{id:'iq_10',level:'IQ',title:'Итог: IQ-система',theory:'**Ежедневно:**\n1. 10 мин N-back\n2. 5 логических задач\n3. 1 шахматная партия\n4. 10 мин скорочтения\n5. 1 аналогия\n\n**Через 3 месяца:** IQ +10-15 баллов.',practice:'Составь расписание IQ-тренировок на неделю.',memory:'IQ тренируется как мышца.',keywords:'IQ system'}
];

/* ============ EQ_MODULE ============ */
var EQ_MODULE=[
{id:'eq_01',level:'EQ',title:'Что такое EQ',theory:'**EQ = эмоциональный интеллект.**\n\n**5 компонентов (Гоулман):**\n1. Самосознание\n2. Саморегуляция\n3. Мотивация\n4. Эмпатия\n5. Социальные навыки\n\n**EQ важнее IQ для успеха в 2 раза.**',practice:'Оцени свой EQ по 5 компонентам (1-10). Запиши.',memory:'EQ = 5 компонентов. Визуализируй.',keywords:'EQ Goleman'},
{id:'eq_02',level:'EQ',title:'Самосознание',theory:'**Самосознание = понимание своих эмоций.**\n\n**Практика:**\n• Дневник эмоций (3 раза в день)\n• Назови эмоцию (name it to tame it)\n• Шкала 1-10\n• Триггеры\n\n**Пример:** "Я чувствую тревогу 7/10, триггер — дедлайн."',practice:'Дневник эмоций 7 дней. 3 записи в день.',memory:'Назови = укроти. Мозг успокаивается.',keywords:'self-awareness'},
{id:'eq_03',level:'EQ',title:'Саморегуляция',theory:'**Техники:**\n• Дыхание 4-7-8\n• Пауза 6 секунд\n• Переоценка (reappraisal)\n• Физическая активность\n• Холодная вода\n\n**Правило:** между стимулом и реакцией — пауза.',practice:'Практикуй паузу 6 секунд в конфликтах. 5 раз за неделю.',memory:'Пауза = свобода выбора.',keywords:'self-regulation'},
{id:'eq_04',level:'EQ',title:'Эмпатия',theory:'**3 типа:**\n• Когнитивная (понимаю)\n• Эмоциональная (чувствую)\n• Сострадательная (действую)\n\n**Практика:**\n• Слушай без перебивания\n• Парафраз\n• "Я слышу тебя"\n• Не давай советов сразу',practice:'Проведи 3 разговора в режиме активного слушания.',memory:'Эмпатия = встать на место другого.',keywords:'empathy'},
{id:'eq_05',level:'EQ',title:'Мотивация',theory:'**Внутренняя vs внешняя.**\n\n**Теория самодетерминации (Деси, Райан):**\n• Автономия\n• Компетентность\n• Связанность\n\n**Практика:** найди внутренний смысл в задаче.',practice:'Для 5 задач найди внутренний смысл. Запиши.',memory:'Внутренняя мотивация = топливо.',keywords:'motivation'},
{id:'eq_06',level:'EQ',title:'Социальные навыки',theory:'**Ключевые:**\n• Влияние\n• Коммуникация\n• Управление конфликтами\n• Лидерство\n• Изменения\n\n**Практика:**\n• Я-сообщения\n• SBI (Situation-Behavior-Impact)\n• ННО (ненасильственное общение)',practice:'Дай обратную связь по SBI 3 раза.',memory:'Социальные = навыки. Тренируются.',keywords:'social skills'},
{id:'eq_07',level:'EQ',title:'Управление стрессом',theory:'**Стресс = реакция.**\n\n**Техники:**\n• Box breathing (4-4-4-4)\n• Прогрессивная релаксация\n• Визуализация\n• Природа 2 ч/нед\n• Спорт\n\n**Гормоны:** кортизол ↓, эндорфины ↑.',practice:'Практикуй 3 техники за неделю. Запиши эффект.',memory:'Стресс управляем.',keywords:'stress management'},
{id:'eq_08',level:'EQ',title:'Конфликты',theory:'**Стили (Томас-Килманн):**\n• Соперничество\n• Избегание\n• Компромисс\n• Сотрудничество\n• Приспособление\n\n**Лучший:** сотрудничество (win-win).',practice:'Разбери 3 конфликта по стилям. Что можно было иначе?',memory:'Сотрудничество = 1+1=3.',keywords:'conflicts'},
{id:'eq_09',level:'EQ',title:'Границы',theory:'**Здоровые границы:**\n• "Нет" без вины\n• "Мне нужно время"\n• "Это не моя ответственность"\n• "Я не готов"\n\n**Формула:** "Я не могу X, но могу Y."',practice:'Скажи "нет" 3 раза за неделю. Запиши реакцию.',memory:'Границы = уважение к себе.',keywords:'boundaries'},
{id:'eq_10',level:'EQ',title:'Итог: EQ-система',theory:'**Ежедневно:**\n1. Дневник эмоций\n2. 1 пауза 6 сек\n3. 1 активное слушание\n4. 1 я-сообщение\n5. 10 мин медитации\n\n**Через месяц:** EQ +20%.',practice:'Составь EQ-расписание на неделю.',memory:'EQ = навык. Тренируй.',keywords:'EQ system'}
];

/* ============ FINANCE_MODULE ============ */
var FINANCE_MODULE=[
{id:'fin_01',level:'Finance',title:'Основы финансов',theory:'**4 столпа:**\n1. Доход\n2. Расходы\n3. Сбережения\n4. Инвестиции\n\n**Правило 50/30/20:**\n• 50% нужды\n• 30% желания\n• 20% сбережения\n\n**Подушка:** 3-6 месяцев расходов.',practice:'Посчитай свой бюджет по 50/30/20. Запиши.',memory:'50/30/20 = карта.',keywords:'finance basics'},
{id:'fin_02',level:'Finance',title:'Учёт расходов',theory:'**Методы:**\n• Приложения (CoinKeeper, Monefy)\n• Таблица Excel\n• Конверты (наличные)\n• Правило 24 часов\n\n**Правило:** записывай каждую трату.',practice:'Записывай все расходы 7 дней. Проанализируй.',memory:'Учёт = контроль.',keywords:'budgeting'},
{id:'fin_03',level:'Finance',title:'Долги',theory:'**2 метода:**\n• Снежный ком (мелкий долг первый)\n• Лавина (высокий % первый)\n\n**Правило:** минимум по всем, максимум по одному.\n\n**Рефинансирование:** снизить %.',practice:'Список долгов. Выбери метод. Составь план.',memory:'Долг = минус. Убирай.',keywords:'debt'},
{id:'fin_04',level:'Finance',title:'Инвестиции',theory:'**Принципы:**\n• Долгосрочно (10+ лет)\n• Диверсификация\n• Индексные фонды\n• Регулярно (DCA)\n• Не пытайся угадать рынок\n\n**Сложный процент:** 10% годовых → ×2 за 7 лет.',practice:'Изучи 3 индексных фонда. Посчитай сложный процент.',memory:'Инвестиции = время + дисциплина.',keywords:'investing'},
{id:'fin_05',level:'Finance',title:'Финансовая независимость (FIRE)',theory:'**FIRE = Financial Independence, Retire Early.**\n\n**Формула:**\n• Норма сбережений 50%+\n• 25× годовых расходов\n• 4% правило вывода\n\n**Пример:** расходы 50к/мес → нужно 15 млн.',practice:'Посчитай свой FIRE-число. Составь план.',memory:'FIRE = свобода.',keywords:'FIRE'},
{id:'fin_06',level:'Finance',title:'Доход',theory:'**Источники:**\n• Основная работа\n• Фриланс\n• Пассивный доход\n• Инвестиции\n• Бизнес\n\n**Правило:** 3+ источника дохода.',practice:'Найди 2 идеи доп. дохода. Составь план.',memory:'Доход = множественный.',keywords:'income'},
{id:'fin_07',level:'Finance',title:'Налоги и вычеты',theory:'**В РФ:**\n• НДФЛ 13-15%\n• ИИС (инвестиционный)\n• Вычеты: обучение, лечение, имущество\n• Самозанятость 4-6%\n\n**Правило:** используй вычеты — верни до 15%.',practice:'Проверь, какие вычеты тебе доступны.',memory:'Налоги = законно оптимизируй.',keywords:'taxes'},
{id:'fin_08',level:'Finance',title:'Финансовые цели',theory:'**SMART-цели:**\n• Specific\n• Measurable\n• Achievable\n• Relevant\n• Time-bound\n\n**Пример:** "Накопить 500к за 12 месяцев, откладывая 42к/мес."',practice:'Поставь 3 финансовые цели по SMART.',memory:'Цель = цифра + срок.',keywords:'goals'},
{id:'fin_09',level:'Finance',title:'Психология денег',theory:'**Ловушки:**\n• Импульсивные покупки\n• Lifestyle inflation\n• FOMO\n• Эмоциональные траты\n\n**Правило 24 часов:** подожди перед покупкой.',practice:'Применяй правило 24 часов неделю. Запиши экономию.',memory:'Деньги = эмоции. Управляй.',keywords:'money psychology'},
{id:'fin_10',level:'Finance',title:'Итог: финансовая система',theory:'**Твоя система:**\n1. Учёт расходов\n2. Бюджет 50/30/20\n3. Подушка 3-6 мес\n4. Долги по лавине\n5. Инвестиции 20%\n6. 3+ источника дохода\n7. Вычеты\n\n**Через год:** +30% к капиталу.',practice:'Составь личный финплан на год.',memory:'Система > удача.',keywords:'finance system'}
];

/* ============ NEURO_MODULE ============ */
var NEURO_MODULE=[
{id:'neuro_01',level:'Neuro',title:'Как учится мозг',theory:'**Нейропластичность:** мозг меняется всю жизнь.\n\n**Синапсы:** связь между нейронами. Чем чаще — тем сильнее.\n\n**Правило Хебба:** "Fire together, wire together."\n\n**Миелин:** ускоряет сигнал в 100 раз.',practice:'Учи 1 навык 30 дней по 15 мин. Отслеживай.',memory:'Мозг = мышца. Тренируй.',keywords:'neuroplasticity'},
{id:'neuro_02',level:'Neuro',title:'Дофамин и мотивация',theory:'**Дофамин = предвкушение, не награда.**\n\n**Проблема:** соцсети, игры, сахар → дофаминовые ямы.\n\n**Решение:**\n• Дофаминовое голодание\n• Скука полезна\n• Награда после усилия\n• Утро без телефона',practice:'Проведи дофаминовое голодание 4 часа. Запиши эффект.',memory:'Дофамин = топливо. Управляй.',keywords:'dopamine'},
{id:'neuro_03',level:'Neuro',title:'Сон и обучение',theory:'**Фазы сна:**\n• NREM (медленный) — факты\n• REM — эмоции, креатив\n\n**Консолидация:** во сне мозг переносит из краткосрочной в долгосрочную.\n\n**Правило:** 7-9 часов. Учи перед сном.',practice:'Учи 10 слов перед сном. Проверь утром.',memory:'Сон = обучение.',keywords:'sleep learning'},
{id:'neuro_04',level:'Neuro',title:'Стресс и обучение',theory:'**Оптимальный стресс:**\n• Слишком мало → скука\n• Слишком много → блок\n• Средний → поток\n\n**Кортизол:** хронический стресс убивает нейроны гиппокампа.\n\n**Решение:** спорт, медитация, сон, природа.',practice:'Найди свой оптимальный уровень стресса для учёбы.',memory:'Стресс = дозируй.',keywords:'stress learning'},
{id:'neuro_05',level:'Neuro',title:'Питание для мозга',theory:'**Топ-продукты:**\n• Omega-3 (рыба, орехи)\n• Ягоды (антиоксиданты)\n• Тёмный шоколад 70%+\n• Зелёный чай\n• Яйца (холин)\n• Куркума\n\n**Избегать:** сахар, трансжиры, алкоголь.',practice:'Добавь 3 продукта в рацион на неделю.',memory:'Мозг = 60% жира. Корми правильно.',keywords:'brain nutrition'},
{id:'neuro_06',level:'Neuro',title:'Физические упражнения',theory:'**BDNF (brain-derived neurotrophic factor):** "удобрение для мозга".\n\n**Эффект:**\n• Аэробные 30 мин → +20% памяти\n• Силовые → +исполнительные функции\n• Прогулка → +креативность\n\n**Правило:** 150 мин кардио + 2 силовые в неделю.',practice:'30 мин кардио перед учёбой. Запиши эффект.',memory:'Движение = мозг.',keywords:'exercise brain'},
{id:'neuro_07',level:'Neuro',title:'Медитация и мозг',theory:'**Эффекты:**\n• Утолщение префронтальной коры\n• Уменьшение миндалины\n• +внимание, +эмпатия\n• -тревога, -стресс\n\n**Доза:** 10-20 мин/день, 8 недель.',practice:'Медитируй 10 мин/день 8 недель. Замерь изменения.',memory:'Медитация = фитнес для мозга.',keywords:'meditation'},
{id:'neuro_08',level:'Neuro',title:'Внимание и фокус',theory:'**Типы внимания:**\n• Фокус (1 задача)\n• Рассеянное (творчество)\n• Переключение (дорого!)\n\n**Стоимость переключения:** 23 минуты на возврат.\n\n**Правило:** одна задача за раз.',practice:'Работай 90 мин с одной задачей. Без телефона.',memory:'Фокус = валюта XXI века.',keywords:'attention focus'},
{id:'neuro_09',level:'Neuro',title:'Креативность',theory:'**Default Mode Network:** активна в покое.\n\n**Техники:**\n• Прогулка\n• Душ\n• Скука\n• Смена обстановки\n• Медитация\n\n**Правило:** креатив требует простоя.',practice:'Прогулка 30 мин без телефона. Запиши идеи.',memory:'Креатив = покой + опыт.',keywords:'creativity'},
{id:'neuro_10',level:'Neuro',title:'Итог: нейро-система',theory:'**Оптимизация:**\n1. Сон 7-9 ч\n2. Спорт 150 мин\n3. Медитация 10 мин\n4. Питание для мозга\n5. Фокус 90 мин\n6. Дофамин-контроль\n7. Стресс-менеджмент\n\n**Через 3 месяца:** мозг работает в 2 раза эффективнее.',practice:'Составь нейро-расписание на неделю.',memory:'Мозг = орган. Ухаживай.',keywords:'neuro system'}
];

/* ============ ОБЪЕДИНЕНИЕ ============ */
var ALL_LESSONS=ENGLISH_125.concat(MEMORY_MODULE,IQ_MODULE,EQ_MODULE,FINANCE_MODULE,NEURO_MODULE);

window.__ENGLISH_125=ENGLISH_125;
window.__ALL_LESSONS=ALL_LESSONS;
window.__MEMORY_MODULE=MEMORY_MODULE;
window.__IQ_MODULE=IQ_MODULE;
window.__EQ_MODULE=EQ_MODULE;
window.__FINANCE_MODULE=FINANCE_MODULE;
window.__NEURO_MODULE=NEURO_MODULE;